INFO - 2021-08-31 19:29:05,081 - new_apply_order.py[line:517]: 开始第 Mipeso【1】次进件……
INFO - 2021-08-31 19:29:05,270 - new_apply_order.py[line:74]: 更新脏数据0条
INFO - 2021-08-31 19:29:05,271 - new_apply_order.py[line:79]: ======【mx测试环境】生成手机号：1630409345 ======
INFO - 2021-08-31 19:29:05,641 - new_apply_order.py[line:86]: 1630409345 检测用户存在成功！
INFO - 2021-08-31 19:29:05,697 - new_apply_order.py[line:93]: 1630409345 短信发送成功！
INFO - 2021-08-31 19:29:05,741 - new_apply_order.py[line:103]: 1630409345 注册成功！
INFO - 2021-08-31 19:29:05,799 - new_apply_order.py[line:113]: 1630409345 登录短信发送成功！
INFO - 2021-08-31 19:29:05,848 - new_apply_order.py[line:121]: userId=4945764994465275904,mobile=1630409345,token=dc8c7456c53bba8728ff6467f9b67135 登录成功
INFO - 2021-08-31 19:29:05,925 - new_apply_order.py[line:172]: 个人信息提交成功！
INFO - 2021-08-31 19:29:06,995 - new_apply_order.py[line:198]: 创建预审订单成功！
INFO - 2021-08-31 19:29:07,009 - new_apply_order.py[line:206]: 预审状态修改为通过,更新条数 1
INFO - 2021-08-31 19:29:07,020 - new_apply_order.py[line:209]: 更新初始额度！更新条数 1
INFO - 2021-08-31 19:29:09,446 - new_apply_order.py[line:237]: curp上传成功!
INFO - 2021-08-31 19:29:09,575 - new_apply_order.py[line:244]: curp_rfc校验通过！
INFO - 2021-08-31 19:29:10,408 - new_apply_order.py[line:253]: 人脸识别成功!
INFO - 2021-08-31 19:29:10,984 - new_apply_order.py[line:302]: 绑卡成功！
INFO - 2021-08-31 19:29:11,163 - new_apply_order.py[line:317]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-08-31 19:29:12,194 - new_apply_order.py[line:323]: 订单表更新1条，信审更新1条
INFO - 2021-08-31 19:29:12,536 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 19:29:12,579 - new_apply_order.py[line:342]: 订单回调复审通过成功！
INFO - 2021-08-31 19:29:13,387 - new_apply_order.py[line:358]: 获取token成功！token=bearer 77a704ec-a17f-40c7-891e-9c8e751ff0ae！
INFO - 2021-08-31 19:29:13,728 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 19:29:14,246 - new_apply_order.py[line:370]: 后台已触发放款成功！
INFO - 2021-08-31 19:29:14,257 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 19:29:14,264 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 19:29:15,655 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 19:29:15,665 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 19:29:15,672 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 19:29:16,015 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 19:29:16,327 - new_apply_order.py[line:540]: 校验重试查询第1次
ERROR - 2021-08-31 19:29:17,341 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-08-31 19:29:17,342 - new_apply_order.py[line:437]: {'app': 'Mipeso', 'loan_order_id': '1432666751856414720', 'mobile': '1630409345', 'order_status': 35}
INFO - 2021-08-31 19:29:18,189 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 19:29:18,302 - new_apply_order.py[line:409]: 放款回调成功！
INFO - 2021-08-31 19:29:18,303 - new_apply_order.py[line:540]: 校验重试查询第2次
INFO - 2021-08-31 19:29:19,318 - new_apply_order.py[line:434]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-08-31 19:29:19,318 - new_apply_order.py[line:437]: {'app': 'Mipeso', 'loan_order_id': '1432666751856414720', 'mobile': '1630409345', 'order_status': 40}
INFO - 2021-08-31 19:29:19,320 - new_apply_order.py[line:557]: ===========完成第【1】次进件===========
INFO - 2021-08-31 19:29:19,320 - new_apply_order.py[line:560]: ======完成第【1】次进件,耗时14.24s=====
INFO - 2021-08-31 19:29:19,442 - new_apply_order.py[line:59]: 删除redis key: "mx:cfs:user:userid:4945764994465275904"
