INFO - 2021-11-25 17:27:50,278 - new_apply_order.py[line:882]: 开始第 G_Prestamo【1】次进件……
INFO - 2021-11-25 17:27:50,347 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4976893288099487744"
INFO - 2021-11-25 17:27:50,383 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4976893689863479296"
INFO - 2021-11-25 17:27:50,398 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4976881282076254208"
INFO - 2021-11-25 17:27:50,449 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-11-25 17:27:50,450 - new_apply_order.py[line:84]: ======【mx测试环境】生成手机号：1637832470 ======
INFO - 2021-11-25 17:27:50,843 - new_apply_order.py[line:97]: 1637832470 检测用户存在成功！
INFO - 2021-11-25 17:27:50,910 - new_apply_order.py[line:106]: 1637832470 短信发送成功！
INFO - 2021-11-25 17:27:50,966 - new_apply_order.py[line:119]: 1637832470 注册成功！
INFO - 2021-11-25 17:27:51,027 - new_apply_order.py[line:135]: 1637832470 登录短信发送成功！
INFO - 2021-11-25 17:27:51,077 - new_apply_order.py[line:145]: userId=4976899838302101504,mobile=1637832470,token=a99bd57349e586d281bbdcc2e8f35e2a 登录成功
INFO - 2021-11-25 17:27:51,177 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-11-25 17:27:51,728 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-11-25 17:27:51,747 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-11-25 17:27:51,763 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-11-25 17:27:54,154 - new_apply_order.py[line:361]: curp上传成功!
INFO - 2021-11-25 17:27:54,313 - new_apply_order.py[line:370]: curp_rfc校验通过！
INFO - 2021-11-25 17:27:55,136 - new_apply_order.py[line:381]: 人脸识别成功!
INFO - 2021-11-25 17:27:55,754 - new_apply_order.py[line:568]: 绑卡成功！
INFO - 2021-11-25 17:27:56,001 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-11-25 17:27:57,030 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-11-25 17:27:57,383 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-11-25 17:27:57,430 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-11-25 17:27:58,222 - new_apply_order.py[line:669]: 获取token成功！token=bearer feb0ceed-beb0-4bda-8a88-c315c6ee0134！
INFO - 2021-11-25 17:27:58,575 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-11-25 17:27:59,151 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-11-25 17:27:59,171 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-11-25 17:27:59,186 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-11-25 17:28:00,537 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-11-25 17:28:00,549 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-11-25 17:28:00,557 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-11-25 17:28:00,915 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-11-25 17:28:01,230 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-11-25 17:28:02,244 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-11-25 17:28:02,244 - new_apply_order.py[line:802]: {'app': 'G_Prestamo', 'loan_order_id': '1463801595999948800', 'mobile': '1637832470', 'order_status': 35}
INFO - 2021-11-25 17:28:03,097 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-11-25 17:28:03,234 - new_apply_order.py[line:754]: 放款回调成功！
INFO - 2021-11-25 17:28:03,235 - new_apply_order.py[line:905]: 校验重试查询第2次
INFO - 2021-11-25 17:28:04,248 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-11-25 17:28:04,249 - new_apply_order.py[line:802]: {'app': 'G_Prestamo', 'loan_order_id': '1463801595999948800', 'mobile': '1637832470', 'order_status': 40}
INFO - 2021-11-25 17:28:04,250 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-11-25 17:28:04,251 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时13.97s=====
