INFO - 2021-10-20 09:01:25,098 - new_apply_order.py[line:882]: 开始第 Mipeso【1】次进件……
INFO - 2021-10-20 09:01:25,263 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-10-20 09:01:25,263 - new_apply_order.py[line:84]: ======【mx测试环境】生成手机号：1634691685 ======
INFO - 2021-10-20 09:01:25,689 - new_apply_order.py[line:97]: 1634691685 检测用户存在成功！
INFO - 2021-10-20 09:01:25,757 - new_apply_order.py[line:106]: 1634691685 短信发送成功！
INFO - 2021-10-20 09:01:25,819 - new_apply_order.py[line:119]: 1634691685 注册成功！
INFO - 2021-10-20 09:01:25,884 - new_apply_order.py[line:135]: 1634691685 登录短信发送成功！
INFO - 2021-10-20 09:01:25,942 - new_apply_order.py[line:145]: userId=4963726430634909696,mobile=1634691685,token=c847488887a2ddd3ed2900cfc4e11c1f 登录成功
INFO - 2021-10-20 09:01:26,036 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:01:26,569 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:01:26,590 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:01:26,610 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:01:28,984 - new_apply_order.py[line:361]: curp上传成功!
INFO - 2021-10-20 09:01:29,137 - new_apply_order.py[line:370]: curp_rfc校验通过！
INFO - 2021-10-20 09:01:29,940 - new_apply_order.py[line:381]: 人脸识别成功!
INFO - 2021-10-20 09:01:30,542 - new_apply_order.py[line:568]: 绑卡成功！
INFO - 2021-10-20 09:01:30,748 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:01:31,790 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:01:32,208 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:01:32,262 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:01:33,111 - new_apply_order.py[line:669]: 获取token成功！token=bearer bb036d87-27c4-42f6-bcb5-eca6742a9aef！
INFO - 2021-10-20 09:01:33,461 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:01:35,110 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:01:35,210 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:01:35,261 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:01:36,744 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:01:36,816 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:01:36,851 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:01:37,210 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:01:37,533 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:01:38,547 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-10-20 09:01:38,548 - new_apply_order.py[line:802]: {'app': 'Mipeso', 'loan_order_id': '1450628188199456768', 'mobile': '1634691685', 'order_status': 32}
INFO - 2021-10-20 09:01:38,556 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:01:38,563 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:01:39,918 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:01:39,935 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:01:39,942 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:01:40,443 - new_apply_order.py[line:905]: 校验重试查询第2次
ERROR - 2021-10-20 09:01:41,464 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:01:41,465 - new_apply_order.py[line:802]: {'app': 'Mipeso', 'loan_order_id': '1450628188199456768', 'mobile': '1634691685', 'order_status': 35}
INFO - 2021-10-20 09:01:42,332 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:01:42,494 - new_apply_order.py[line:754]: 放款回调成功！
INFO - 2021-10-20 09:01:42,494 - new_apply_order.py[line:905]: 校验重试查询第3次
INFO - 2021-10-20 09:01:43,514 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-10-20 09:01:43,514 - new_apply_order.py[line:802]: {'app': 'Mipeso', 'loan_order_id': '1450628188199456768', 'mobile': '1634691685', 'order_status': 40}
INFO - 2021-10-20 09:01:43,517 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:01:43,517 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时18.42s=====
INFO - 2021-10-20 09:01:43,521 - new_apply_order.py[line:882]: 开始第 m_efectivo【1】次进件……
INFO - 2021-10-20 09:01:43,609 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4963726430634909696"
INFO - 2021-10-20 09:01:43,706 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-10-20 09:01:43,707 - new_apply_order.py[line:84]: ======【mx测试环境】生成手机号：1634691703 ======
INFO - 2021-10-20 09:01:44,058 - new_apply_order.py[line:97]: 1634691703 检测用户存在成功！
INFO - 2021-10-20 09:01:44,120 - new_apply_order.py[line:106]: 1634691703 短信发送成功！
INFO - 2021-10-20 09:01:44,176 - new_apply_order.py[line:119]: 1634691703 注册成功！
INFO - 2021-10-20 09:01:44,275 - new_apply_order.py[line:135]: 1634691703 登录短信发送成功！
INFO - 2021-10-20 09:01:44,330 - new_apply_order.py[line:145]: userId=4963726507612971008,mobile=1634691703,token=cf84330d535b8e1431c6ebb2d3678020 登录成功
INFO - 2021-10-20 09:01:44,444 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:01:44,810 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:01:44,830 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:01:44,855 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:01:47,304 - new_apply_order.py[line:361]: curp上传成功!
INFO - 2021-10-20 09:01:47,438 - new_apply_order.py[line:370]: curp_rfc校验通过！
INFO - 2021-10-20 09:01:48,306 - new_apply_order.py[line:381]: 人脸识别成功!
INFO - 2021-10-20 09:01:49,112 - new_apply_order.py[line:568]: 绑卡成功！
INFO - 2021-10-20 09:01:49,300 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:01:50,334 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:01:50,681 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:01:50,718 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:01:51,510 - new_apply_order.py[line:669]: 获取token成功！token=bearer bb036d87-27c4-42f6-bcb5-eca6742a9aef！
INFO - 2021-10-20 09:01:51,856 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:01:52,142 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:01:52,154 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:01:52,173 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:01:53,526 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:01:53,545 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:01:53,551 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:01:53,902 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:01:54,214 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:01:55,244 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:01:55,244 - new_apply_order.py[line:802]: {'app': 'm_efectivo', 'loan_order_id': '1450628265433370624', 'mobile': '1634691703', 'order_status': 35}
INFO - 2021-10-20 09:01:56,088 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:01:56,186 - new_apply_order.py[line:754]: 放款回调成功！
INFO - 2021-10-20 09:01:56,186 - new_apply_order.py[line:905]: 校验重试查询第2次
INFO - 2021-10-20 09:01:57,199 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-10-20 09:01:57,199 - new_apply_order.py[line:802]: {'app': 'm_efectivo', 'loan_order_id': '1450628265433370624', 'mobile': '1634691703', 'order_status': 40}
INFO - 2021-10-20 09:01:57,200 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:01:57,200 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时13.68s=====
INFO - 2021-10-20 09:01:57,204 - new_apply_order.py[line:882]: 开始第 porpeso【1】次进件……
INFO - 2021-10-20 09:01:57,263 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4963726507612971008"
INFO - 2021-10-20 09:01:57,389 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-10-20 09:01:57,390 - new_apply_order.py[line:84]: ======【mx测试环境】生成手机号：1634691717 ======
INFO - 2021-10-20 09:01:57,739 - new_apply_order.py[line:97]: 1634691717 检测用户存在成功！
INFO - 2021-10-20 09:01:57,788 - new_apply_order.py[line:106]: 1634691717 短信发送成功！
INFO - 2021-10-20 09:01:57,854 - new_apply_order.py[line:119]: 1634691717 注册成功！
INFO - 2021-10-20 09:01:57,908 - new_apply_order.py[line:135]: 1634691717 登录短信发送成功！
INFO - 2021-10-20 09:01:57,951 - new_apply_order.py[line:145]: userId=4963726565012021248,mobile=1634691717,token=cf6e7761d225cb7300637e8d754428ef 登录成功
INFO - 2021-10-20 09:01:58,024 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:01:58,439 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:01:58,456 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:01:58,470 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:02:00,848 - new_apply_order.py[line:361]: curp上传成功!
INFO - 2021-10-20 09:02:00,990 - new_apply_order.py[line:370]: curp_rfc校验通过！
INFO - 2021-10-20 09:02:01,807 - new_apply_order.py[line:381]: 人脸识别成功!
INFO - 2021-10-20 09:02:02,349 - new_apply_order.py[line:568]: 绑卡成功！
INFO - 2021-10-20 09:02:02,535 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:02:03,570 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:02:03,938 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:03,973 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:02:04,794 - new_apply_order.py[line:669]: 获取token成功！token=bearer bb036d87-27c4-42f6-bcb5-eca6742a9aef！
INFO - 2021-10-20 09:02:05,143 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:05,473 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:02:05,487 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:02:05,498 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:02:06,861 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:06,876 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:02:06,884 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:02:07,235 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:07,551 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:02:08,566 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:02:08,566 - new_apply_order.py[line:802]: {'app': 'porpeso', 'loan_order_id': '1450628322358464512', 'mobile': '1634691717', 'order_status': 35}
INFO - 2021-10-20 09:02:09,421 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:09,512 - new_apply_order.py[line:754]: 放款回调成功！
INFO - 2021-10-20 09:02:09,512 - new_apply_order.py[line:905]: 校验重试查询第2次
INFO - 2021-10-20 09:02:10,530 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-10-20 09:02:10,530 - new_apply_order.py[line:802]: {'app': 'porpeso', 'loan_order_id': '1450628322358464512', 'mobile': '1634691717', 'order_status': 40}
INFO - 2021-10-20 09:02:10,531 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:02:10,531 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时13.33s=====
INFO - 2021-10-20 09:02:10,535 - new_apply_order.py[line:882]: 开始第 Prestamo【1】次进件……
INFO - 2021-10-20 09:02:10,688 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4963726565012021248"
INFO - 2021-10-20 09:02:10,710 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-10-20 09:02:10,711 - new_apply_order.py[line:84]: ======【mx测试环境】生成手机号：1634691730 ======
INFO - 2021-10-20 09:02:11,074 - new_apply_order.py[line:97]: 1634691730 检测用户存在成功！
INFO - 2021-10-20 09:02:11,120 - new_apply_order.py[line:106]: 1634691730 短信发送成功！
INFO - 2021-10-20 09:02:11,158 - new_apply_order.py[line:119]: 1634691730 注册成功！
INFO - 2021-10-20 09:02:11,207 - new_apply_order.py[line:135]: 1634691730 登录短信发送成功！
INFO - 2021-10-20 09:02:11,256 - new_apply_order.py[line:145]: userId=4963726620834013184,mobile=1634691730,token=e2246d03460a503da38101325584d766 登录成功
INFO - 2021-10-20 09:02:11,333 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:02:11,534 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:02:11,552 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:02:11,568 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:02:13,957 - new_apply_order.py[line:361]: curp上传成功!
INFO - 2021-10-20 09:02:14,098 - new_apply_order.py[line:370]: curp_rfc校验通过！
INFO - 2021-10-20 09:02:14,811 - new_apply_order.py[line:381]: 人脸识别成功!
INFO - 2021-10-20 09:02:15,359 - new_apply_order.py[line:568]: 绑卡成功！
INFO - 2021-10-20 09:02:15,531 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:02:16,561 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:02:16,912 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:16,949 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:02:17,731 - new_apply_order.py[line:669]: 获取token成功！token=bearer bb036d87-27c4-42f6-bcb5-eca6742a9aef！
INFO - 2021-10-20 09:02:18,078 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:18,388 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:02:18,400 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:02:18,410 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:02:19,763 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:19,777 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:02:19,784 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:02:20,127 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:20,442 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:02:21,455 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:02:21,456 - new_apply_order.py[line:802]: {'app': 'Prestamo', 'loan_order_id': '1450628378172067840', 'mobile': '1634691730', 'order_status': 35}
INFO - 2021-10-20 09:02:22,308 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:22,394 - new_apply_order.py[line:754]: 放款回调成功！
INFO - 2021-10-20 09:02:22,394 - new_apply_order.py[line:905]: 校验重试查询第2次
INFO - 2021-10-20 09:02:23,411 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-10-20 09:02:23,412 - new_apply_order.py[line:802]: {'app': 'Prestamo', 'loan_order_id': '1450628378172067840', 'mobile': '1634691730', 'order_status': 40}
INFO - 2021-10-20 09:02:23,412 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:02:23,412 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时12.88s=====
INFO - 2021-10-20 09:02:23,416 - new_apply_order.py[line:882]: 开始第 askborrow【1】次进件……
INFO - 2021-10-20 09:02:23,493 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4963726620834013184"
INFO - 2021-10-20 09:02:23,586 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-10-20 09:02:23,586 - new_apply_order.py[line:84]: ======【mx测试环境】生成手机号：1634691743 ======
INFO - 2021-10-20 09:02:23,933 - new_apply_order.py[line:97]: 1634691743 检测用户存在成功！
INFO - 2021-10-20 09:02:23,978 - new_apply_order.py[line:106]: 1634691743 短信发送成功！
INFO - 2021-10-20 09:02:24,022 - new_apply_order.py[line:119]: 1634691743 注册成功！
INFO - 2021-10-20 09:02:24,078 - new_apply_order.py[line:135]: 1634691743 登录短信发送成功！
INFO - 2021-10-20 09:02:24,127 - new_apply_order.py[line:145]: userId=4963726674768568320,mobile=1634691743,token=72c0003179244ae52442fb37ee20a8ec 登录成功
INFO - 2021-10-20 09:02:24,204 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:02:24,578 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:02:24,592 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:02:24,600 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:02:27,017 - new_apply_order.py[line:361]: curp上传成功!
INFO - 2021-10-20 09:02:27,132 - new_apply_order.py[line:370]: curp_rfc校验通过！
INFO - 2021-10-20 09:02:27,884 - new_apply_order.py[line:381]: 人脸识别成功!
INFO - 2021-10-20 09:02:28,458 - new_apply_order.py[line:568]: 绑卡成功！
INFO - 2021-10-20 09:02:28,612 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:02:29,639 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:02:29,986 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:30,028 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:02:30,826 - new_apply_order.py[line:669]: 获取token成功！token=bearer bb036d87-27c4-42f6-bcb5-eca6742a9aef！
INFO - 2021-10-20 09:02:31,165 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:31,486 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:02:31,494 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:02:31,500 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:02:32,843 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:32,856 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:02:32,861 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:02:33,203 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:33,514 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:02:34,524 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:02:34,524 - new_apply_order.py[line:802]: {'app': 'askborrow', 'loan_order_id': '1450628432165343232', 'mobile': '1634691743', 'order_status': 35}
INFO - 2021-10-20 09:02:35,384 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:35,391 - new_apply_order.py[line:905]: 校验重试查询第2次
ERROR - 2021-10-20 09:02:36,403 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:02:36,403 - new_apply_order.py[line:802]: {'app': 'askborrow', 'loan_order_id': '1450628432165343232', 'mobile': '1634691743', 'order_status': 35}
INFO - 2021-10-20 09:02:37,255 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:37,262 - new_apply_order.py[line:905]: 校验重试查询第3次
ERROR - 2021-10-20 09:02:38,273 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:02:38,273 - new_apply_order.py[line:802]: {'app': 'askborrow', 'loan_order_id': '1450628432165343232', 'mobile': '1634691743', 'order_status': 35}
INFO - 2021-10-20 09:02:39,125 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:39,229 - new_apply_order.py[line:754]: 放款回调成功！
INFO - 2021-10-20 09:02:39,230 - new_apply_order.py[line:905]: 校验重试查询第4次
INFO - 2021-10-20 09:02:40,244 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-10-20 09:02:40,244 - new_apply_order.py[line:802]: {'app': 'askborrow', 'loan_order_id': '1450628432165343232', 'mobile': '1634691743', 'order_status': 40}
INFO - 2021-10-20 09:02:40,246 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:02:40,246 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时16.83s=====
INFO - 2021-10-20 09:02:40,250 - new_apply_order.py[line:882]: 开始第 G_Prestamo【1】次进件……
INFO - 2021-10-20 09:02:40,385 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4963726674768568320"
INFO - 2021-10-20 09:02:40,430 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-10-20 09:02:40,430 - new_apply_order.py[line:84]: ======【mx测试环境】生成手机号：1634691760 ======
INFO - 2021-10-20 09:02:40,770 - new_apply_order.py[line:97]: 1634691760 检测用户存在成功！
INFO - 2021-10-20 09:02:40,815 - new_apply_order.py[line:106]: 1634691760 短信发送成功！
INFO - 2021-10-20 09:02:40,857 - new_apply_order.py[line:119]: 1634691760 注册成功！
INFO - 2021-10-20 09:02:40,911 - new_apply_order.py[line:135]: 1634691760 登录短信发送成功！
INFO - 2021-10-20 09:02:40,957 - new_apply_order.py[line:145]: userId=4963726745383870464,mobile=1634691760,token=0d4aaf222375109ee20b02b97f45e9e6 登录成功
INFO - 2021-10-20 09:02:41,033 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:02:41,226 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:02:41,244 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:02:41,258 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:02:43,686 - new_apply_order.py[line:361]: curp上传成功!
INFO - 2021-10-20 09:02:43,819 - new_apply_order.py[line:370]: curp_rfc校验通过！
INFO - 2021-10-20 09:02:44,565 - new_apply_order.py[line:381]: 人脸识别成功!
INFO - 2021-10-20 09:02:45,117 - new_apply_order.py[line:568]: 绑卡成功！
INFO - 2021-10-20 09:02:45,293 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:02:46,332 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:02:46,693 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:46,723 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:02:47,556 - new_apply_order.py[line:669]: 获取token成功！token=bearer bb036d87-27c4-42f6-bcb5-eca6742a9aef！
INFO - 2021-10-20 09:02:47,902 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:48,219 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:02:48,231 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:02:48,240 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:02:49,587 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:49,605 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:02:49,613 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:02:49,982 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:50,298 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:02:51,314 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:02:51,315 - new_apply_order.py[line:802]: {'app': 'G_Prestamo', 'loan_order_id': '1450628502738702336', 'mobile': '1634691760', 'order_status': 35}
INFO - 2021-10-20 09:02:52,164 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:02:52,264 - new_apply_order.py[line:754]: 放款回调成功！
INFO - 2021-10-20 09:02:52,265 - new_apply_order.py[line:905]: 校验重试查询第2次
INFO - 2021-10-20 09:02:53,282 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-10-20 09:02:53,282 - new_apply_order.py[line:802]: {'app': 'G_Prestamo', 'loan_order_id': '1450628502738702336', 'mobile': '1634691760', 'order_status': 40}
INFO - 2021-10-20 09:02:53,283 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:02:53,283 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时13.03s=====
INFO - 2021-10-20 09:02:53,286 - new_apply_order.py[line:882]: 开始第 miprestamo【1】次进件……
INFO - 2021-10-20 09:02:53,436 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4963726745383870464"
INFO - 2021-10-20 09:02:53,454 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-10-20 09:02:53,454 - new_apply_order.py[line:84]: ======【mx测试环境】生成手机号：1634691773 ======
INFO - 2021-10-20 09:02:53,800 - new_apply_order.py[line:97]: 1634691773 检测用户存在成功！
INFO - 2021-10-20 09:02:53,849 - new_apply_order.py[line:106]: 1634691773 短信发送成功！
INFO - 2021-10-20 09:02:53,892 - new_apply_order.py[line:119]: 1634691773 注册成功！
INFO - 2021-10-20 09:02:53,945 - new_apply_order.py[line:135]: 1634691773 登录短信发送成功！
INFO - 2021-10-20 09:02:53,988 - new_apply_order.py[line:145]: userId=4963726800048234496,mobile=1634691773,token=6c3b5e196434f6360cff72421fd7e451 登录成功
INFO - 2021-10-20 09:02:54,059 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:02:54,476 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:02:54,493 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:02:54,508 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:02:57,217 - new_apply_order.py[line:361]: curp上传成功!
INFO - 2021-10-20 09:02:57,337 - new_apply_order.py[line:370]: curp_rfc校验通过！
INFO - 2021-10-20 09:02:58,082 - new_apply_order.py[line:381]: 人脸识别成功!
INFO - 2021-10-20 09:02:58,631 - new_apply_order.py[line:568]: 绑卡成功！
INFO - 2021-10-20 09:02:58,801 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:02:59,834 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:03:00,186 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:00,224 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:03:01,083 - new_apply_order.py[line:669]: 获取token成功！token=bearer bb036d87-27c4-42f6-bcb5-eca6742a9aef！
INFO - 2021-10-20 09:03:01,424 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:01,685 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:03:01,697 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:03:01,708 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:03:03,058 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:03,071 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:03:03,077 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:03:03,424 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:03,737 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:03:04,755 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:03:04,756 - new_apply_order.py[line:802]: {'app': 'miprestamo', 'loan_order_id': '1450628557373706240', 'mobile': '1634691773', 'order_status': 35}
INFO - 2021-10-20 09:03:05,630 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:05,746 - new_apply_order.py[line:754]: 放款回调成功！
INFO - 2021-10-20 09:03:05,746 - new_apply_order.py[line:905]: 校验重试查询第2次
INFO - 2021-10-20 09:03:06,762 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-10-20 09:03:06,763 - new_apply_order.py[line:802]: {'app': 'miprestamo', 'loan_order_id': '1450628557373706240', 'mobile': '1634691773', 'order_status': 40}
INFO - 2021-10-20 09:03:06,763 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:03:06,763 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时13.48s=====
INFO - 2021-10-20 09:03:06,766 - new_apply_order.py[line:882]: 开始第 borrowedpop【1】次进件……
INFO - 2021-10-20 09:03:06,827 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4963726800048234496"
INFO - 2021-10-20 09:03:06,935 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-10-20 09:03:06,935 - new_apply_order.py[line:84]: ======【mx测试环境】生成手机号：1634691786 ======
INFO - 2021-10-20 09:03:07,282 - new_apply_order.py[line:97]: 1634691786 检测用户存在成功！
INFO - 2021-10-20 09:03:07,330 - new_apply_order.py[line:106]: 1634691786 短信发送成功！
INFO - 2021-10-20 09:03:07,371 - new_apply_order.py[line:119]: 1634691786 注册成功！
INFO - 2021-10-20 09:03:07,423 - new_apply_order.py[line:135]: 1634691786 登录短信发送成功！
INFO - 2021-10-20 09:03:07,468 - new_apply_order.py[line:145]: userId=4963726856591646720,mobile=1634691786,token=2c5c8148ec42737b5cbe55d015c9a065 登录成功
INFO - 2021-10-20 09:03:07,546 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:03:07,732 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:03:07,749 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:03:07,765 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:03:10,205 - new_apply_order.py[line:361]: curp上传成功!
INFO - 2021-10-20 09:03:10,325 - new_apply_order.py[line:370]: curp_rfc校验通过！
INFO - 2021-10-20 09:03:11,095 - new_apply_order.py[line:381]: 人脸识别成功!
INFO - 2021-10-20 09:03:11,619 - new_apply_order.py[line:568]: 绑卡成功！
INFO - 2021-10-20 09:03:11,867 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:03:12,900 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:03:13,254 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:13,308 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:03:14,098 - new_apply_order.py[line:669]: 获取token成功！token=bearer bb036d87-27c4-42f6-bcb5-eca6742a9aef！
INFO - 2021-10-20 09:03:14,445 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:14,735 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:03:14,747 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:03:14,756 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:03:16,103 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:16,121 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:03:16,129 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:03:16,483 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:16,798 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:03:17,816 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:03:17,816 - new_apply_order.py[line:802]: {'app': 'borrowedpop', 'loan_order_id': '1450628613963255808', 'mobile': '1634691786', 'order_status': 35}
INFO - 2021-10-20 09:03:18,674 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:18,762 - new_apply_order.py[line:754]: 放款回调成功！
INFO - 2021-10-20 09:03:18,763 - new_apply_order.py[line:905]: 校验重试查询第2次
INFO - 2021-10-20 09:03:19,781 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-10-20 09:03:19,782 - new_apply_order.py[line:802]: {'app': 'borrowedpop', 'loan_order_id': '1450628613963255808', 'mobile': '1634691786', 'order_status': 40}
INFO - 2021-10-20 09:03:19,782 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:03:19,782 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时13.02s=====
INFO - 2021-10-20 09:03:19,786 - new_apply_order.py[line:882]: 开始第 goodloan【1】次进件……
INFO - 2021-10-20 09:03:19,944 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4963726856591646720"
INFO - 2021-10-20 09:03:19,961 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-10-20 09:03:19,962 - new_apply_order.py[line:84]: ======【mx测试环境】生成手机号：1634691799 ======
INFO - 2021-10-20 09:03:20,304 - new_apply_order.py[line:97]: 1634691799 检测用户存在成功！
INFO - 2021-10-20 09:03:20,348 - new_apply_order.py[line:106]: 1634691799 短信发送成功！
INFO - 2021-10-20 09:03:20,388 - new_apply_order.py[line:119]: 1634691799 注册成功！
INFO - 2021-10-20 09:03:20,439 - new_apply_order.py[line:135]: 1634691799 登录短信发送成功！
INFO - 2021-10-20 09:03:20,483 - new_apply_order.py[line:145]: userId=4963726911188901888,mobile=1634691799,token=b3996e98f5218516b30e127ac2f785ff 登录成功
INFO - 2021-10-20 09:03:20,562 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:03:20,743 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:03:20,758 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:03:20,772 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:03:23,222 - new_apply_order.py[line:361]: curp上传成功!
INFO - 2021-10-20 09:03:23,336 - new_apply_order.py[line:370]: curp_rfc校验通过！
INFO - 2021-10-20 09:03:24,058 - new_apply_order.py[line:381]: 人脸识别成功!
INFO - 2021-10-20 09:03:24,629 - new_apply_order.py[line:568]: 绑卡成功！
INFO - 2021-10-20 09:03:24,791 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:03:25,817 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:03:26,165 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:26,202 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:03:26,972 - new_apply_order.py[line:669]: 获取token成功！token=bearer bb036d87-27c4-42f6-bcb5-eca6742a9aef！
INFO - 2021-10-20 09:03:27,319 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:27,649 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:03:27,657 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:03:27,669 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:03:29,020 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:29,035 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:03:29,042 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:03:29,386 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:29,697 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:03:30,713 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:03:30,713 - new_apply_order.py[line:802]: {'app': 'goodloan', 'loan_order_id': '1450628668535345152', 'mobile': '1634691799', 'order_status': 35}
INFO - 2021-10-20 09:03:31,570 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:31,658 - new_apply_order.py[line:754]: 放款回调成功！
INFO - 2021-10-20 09:03:31,658 - new_apply_order.py[line:905]: 校验重试查询第2次
INFO - 2021-10-20 09:03:32,671 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-10-20 09:03:32,672 - new_apply_order.py[line:802]: {'app': 'goodloan', 'loan_order_id': '1450628668535345152', 'mobile': '1634691799', 'order_status': 40}
INFO - 2021-10-20 09:03:32,673 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:03:32,673 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时12.89s=====
INFO - 2021-10-20 09:03:32,676 - new_apply_order.py[line:882]: 开始第 Hola_efectivo【1】次进件……
INFO - 2021-10-20 09:03:32,737 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4963726911188901888"
INFO - 2021-10-20 09:03:32,839 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-10-20 09:03:32,839 - new_apply_order.py[line:84]: ======【mx测试环境】生成手机号：1634691812 ======
INFO - 2021-10-20 09:03:33,187 - new_apply_order.py[line:97]: 1634691812 检测用户存在成功！
INFO - 2021-10-20 09:03:33,236 - new_apply_order.py[line:106]: 1634691812 短信发送成功！
INFO - 2021-10-20 09:03:33,276 - new_apply_order.py[line:119]: 1634691812 注册成功！
INFO - 2021-10-20 09:03:33,332 - new_apply_order.py[line:135]: 1634691812 登录短信发送成功！
INFO - 2021-10-20 09:03:33,386 - new_apply_order.py[line:145]: userId=4963726965249286144,mobile=1634691812,token=4a5ff14fb0f118d9c584cffeb6788a4c 登录成功
INFO - 2021-10-20 09:03:33,465 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:03:33,848 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:03:33,867 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:03:33,884 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:03:36,362 - new_apply_order.py[line:361]: curp上传成功!
INFO - 2021-10-20 09:03:36,484 - new_apply_order.py[line:370]: curp_rfc校验通过！
INFO - 2021-10-20 09:03:37,228 - new_apply_order.py[line:381]: 人脸识别成功!
INFO - 2021-10-20 09:03:37,806 - new_apply_order.py[line:568]: 绑卡成功！
INFO - 2021-10-20 09:03:37,992 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:03:39,020 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:03:39,372 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:39,408 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:03:40,221 - new_apply_order.py[line:669]: 获取token成功！token=bearer bb036d87-27c4-42f6-bcb5-eca6742a9aef！
INFO - 2021-10-20 09:03:40,563 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:40,830 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:03:40,842 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:03:40,854 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:03:42,199 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:42,216 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:03:42,225 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:03:42,573 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:42,887 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:03:43,902 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:03:43,903 - new_apply_order.py[line:802]: {'app': 'Hola_efectivo', 'loan_order_id': '1450628722662838272', 'mobile': '1634691812', 'order_status': 35}
INFO - 2021-10-20 09:03:44,752 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:44,853 - new_apply_order.py[line:754]: 放款回调成功！
INFO - 2021-10-20 09:03:44,854 - new_apply_order.py[line:905]: 校验重试查询第2次
INFO - 2021-10-20 09:03:45,875 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-10-20 09:03:45,876 - new_apply_order.py[line:802]: {'app': 'Hola_efectivo', 'loan_order_id': '1450628722662838272', 'mobile': '1634691812', 'order_status': 40}
INFO - 2021-10-20 09:03:45,877 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:03:45,878 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时13.20s=====
INFO - 2021-10-20 09:03:45,885 - new_apply_order.py[line:882]: 开始第 borrowme【1】次进件……
INFO - 2021-10-20 09:03:45,886 - new_apply_order.py[line:84]: ======【nga测试环境】生成手机号：01634691825 ======
INFO - 2021-10-20 09:03:46,269 - new_apply_order.py[line:97]: 01634691825 检测用户存在成功！
INFO - 2021-10-20 09:03:46,337 - new_apply_order.py[line:106]: 01634691825 短信发送成功！
INFO - 2021-10-20 09:03:46,407 - new_apply_order.py[line:119]: 01634691825 注册成功！
INFO - 2021-10-20 09:03:46,468 - new_apply_order.py[line:135]: 01634691825 登录短信发送成功！
INFO - 2021-10-20 09:03:46,525 - new_apply_order.py[line:145]: userId=6222018220272918528,mobile=01634691825,token=32b4dfb4fde80c64622a1c849206c94d 登录成功
INFO - 2021-10-20 09:03:46,605 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:03:46,658 - new_apply_order.py[line:223]: 联系人信息提交成功！
INFO - 2021-10-20 09:03:47,156 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:03:47,174 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:03:47,190 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:03:47,510 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:03:47,557 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:03:48,601 - new_apply_order.py[line:510]: bvn和银行卡绑卡认证通过！
INFO - 2021-10-20 09:03:48,939 - new_apply_order.py[line:561]: user更新1条
INFO - 2021-10-20 09:03:49,206 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:03:50,248 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:03:50,602 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:50,657 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:03:51,462 - new_apply_order.py[line:669]: 获取token成功！token=bearer 0c58ac73-b149-444c-8e04-0ef7d2554aee！
INFO - 2021-10-20 09:03:51,807 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:52,384 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:03:52,400 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:03:52,415 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:03:53,767 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:03:53,786 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:03:53,795 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:03:54,101 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:03:55,120 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:03:55,120 - new_apply_order.py[line:802]: {'app': 'borrowme', 'loan_order_id': '1450628778201583616', 'mobile': '01634691825', 'order_status': 35}
INFO - 2021-10-20 09:03:55,628 - new_apply_order.py[line:905]: 校验重试查询第2次
ERROR - 2021-10-20 09:03:56,647 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:03:56,648 - new_apply_order.py[line:802]: {'app': 'borrowme', 'loan_order_id': '1450628778201583616', 'mobile': '01634691825', 'order_status': 35}
INFO - 2021-10-20 09:03:57,157 - new_apply_order.py[line:905]: 校验重试查询第3次
ERROR - 2021-10-20 09:03:58,175 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:03:58,175 - new_apply_order.py[line:802]: {'app': 'borrowme', 'loan_order_id': '1450628778201583616', 'mobile': '01634691825', 'order_status': 35}
INFO - 2021-10-20 09:03:58,684 - new_apply_order.py[line:905]: 校验重试查询第4次
ERROR - 2021-10-20 09:03:59,700 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:03:59,700 - new_apply_order.py[line:802]: {'app': 'borrowme', 'loan_order_id': '1450628778201583616', 'mobile': '01634691825', 'order_status': 35}
INFO - 2021-10-20 09:04:00,209 - new_apply_order.py[line:905]: 校验重试查询第5次
ERROR - 2021-10-20 09:04:01,225 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:01,225 - new_apply_order.py[line:802]: {'app': 'borrowme', 'loan_order_id': '1450628778201583616', 'mobile': '01634691825', 'order_status': 35}
INFO - 2021-10-20 09:04:01,734 - new_apply_order.py[line:905]: 校验重试查询第6次
ERROR - 2021-10-20 09:04:02,751 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:02,751 - new_apply_order.py[line:802]: {'app': 'borrowme', 'loan_order_id': '1450628778201583616', 'mobile': '01634691825', 'order_status': 35}
INFO - 2021-10-20 09:04:03,259 - new_apply_order.py[line:905]: 校验重试查询第7次
ERROR - 2021-10-20 09:04:04,274 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:04,274 - new_apply_order.py[line:802]: {'app': 'borrowme', 'loan_order_id': '1450628778201583616', 'mobile': '01634691825', 'order_status': 35}
INFO - 2021-10-20 09:04:04,781 - new_apply_order.py[line:905]: 校验重试查询第8次
ERROR - 2021-10-20 09:04:05,799 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是36
INFO - 2021-10-20 09:04:05,799 - new_apply_order.py[line:802]: {'app': 'borrowme', 'loan_order_id': '1450628778201583616', 'mobile': '01634691825', 'order_status': 36}
INFO - 2021-10-20 09:04:05,800 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:04:05,800 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时19.92s=====
INFO - 2021-10-20 09:04:05,804 - new_apply_order.py[line:882]: 开始第 quickcash【1】次进件……
INFO - 2021-10-20 09:04:05,806 - new_apply_order.py[line:84]: ======【nga测试环境】生成手机号：01634691845 ======
INFO - 2021-10-20 09:04:06,160 - new_apply_order.py[line:97]: 01634691845 检测用户存在成功！
INFO - 2021-10-20 09:04:06,227 - new_apply_order.py[line:106]: 01634691845 短信发送成功！
INFO - 2021-10-20 09:04:06,268 - new_apply_order.py[line:119]: 01634691845 注册成功！
INFO - 2021-10-20 09:04:06,326 - new_apply_order.py[line:135]: 01634691845 登录短信发送成功！
INFO - 2021-10-20 09:04:06,368 - new_apply_order.py[line:145]: userId=6222018303613739008,mobile=01634691845,token=ab0a2231039b8215116ca21af47777d5 登录成功
INFO - 2021-10-20 09:04:06,445 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:04:06,496 - new_apply_order.py[line:223]: 联系人信息提交成功！
INFO - 2021-10-20 09:04:06,764 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:04:06,787 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:04:06,805 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:04:07,104 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:04:07,137 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:04:08,177 - new_apply_order.py[line:510]: bvn和银行卡绑卡认证通过！
INFO - 2021-10-20 09:04:08,509 - new_apply_order.py[line:561]: user更新1条
INFO - 2021-10-20 09:04:08,772 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:04:09,814 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:04:10,169 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:04:10,209 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:04:11,008 - new_apply_order.py[line:669]: 获取token成功！token=bearer 0c58ac73-b149-444c-8e04-0ef7d2554aee！
INFO - 2021-10-20 09:04:11,354 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:04:11,610 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:04:11,624 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:04:11,648 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:04:13,010 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:04:13,024 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:04:13,033 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:04:13,338 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:04:14,353 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:14,353 - new_apply_order.py[line:802]: {'app': 'quickcash', 'loan_order_id': '1450628861219442688', 'mobile': '01634691845', 'order_status': 35}
INFO - 2021-10-20 09:04:14,863 - new_apply_order.py[line:905]: 校验重试查询第2次
ERROR - 2021-10-20 09:04:15,879 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:15,879 - new_apply_order.py[line:802]: {'app': 'quickcash', 'loan_order_id': '1450628861219442688', 'mobile': '01634691845', 'order_status': 35}
INFO - 2021-10-20 09:04:16,384 - new_apply_order.py[line:905]: 校验重试查询第3次
ERROR - 2021-10-20 09:04:17,400 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:17,401 - new_apply_order.py[line:802]: {'app': 'quickcash', 'loan_order_id': '1450628861219442688', 'mobile': '01634691845', 'order_status': 35}
INFO - 2021-10-20 09:04:17,910 - new_apply_order.py[line:905]: 校验重试查询第4次
ERROR - 2021-10-20 09:04:18,924 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:18,924 - new_apply_order.py[line:802]: {'app': 'quickcash', 'loan_order_id': '1450628861219442688', 'mobile': '01634691845', 'order_status': 35}
INFO - 2021-10-20 09:04:19,433 - new_apply_order.py[line:905]: 校验重试查询第5次
ERROR - 2021-10-20 09:04:20,451 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:20,452 - new_apply_order.py[line:802]: {'app': 'quickcash', 'loan_order_id': '1450628861219442688', 'mobile': '01634691845', 'order_status': 35}
INFO - 2021-10-20 09:04:20,960 - new_apply_order.py[line:905]: 校验重试查询第6次
ERROR - 2021-10-20 09:04:21,979 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是36
INFO - 2021-10-20 09:04:21,979 - new_apply_order.py[line:802]: {'app': 'quickcash', 'loan_order_id': '1450628861219442688', 'mobile': '01634691845', 'order_status': 36}
INFO - 2021-10-20 09:04:21,980 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:04:21,980 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时16.18s=====
INFO - 2021-10-20 09:04:21,984 - new_apply_order.py[line:882]: 开始第 borrowme【1】次进件……
INFO - 2021-10-20 09:04:21,986 - new_apply_order.py[line:84]: ======【nga测试环境】生成手机号：01634691861 ======
INFO - 2021-10-20 09:04:22,352 - new_apply_order.py[line:97]: 01634691861 检测用户存在成功！
INFO - 2021-10-20 09:04:22,393 - new_apply_order.py[line:106]: 01634691861 短信发送成功！
INFO - 2021-10-20 09:04:22,427 - new_apply_order.py[line:119]: 01634691861 注册成功！
INFO - 2021-10-20 09:04:22,485 - new_apply_order.py[line:135]: 01634691861 登录短信发送成功！
INFO - 2021-10-20 09:04:22,529 - new_apply_order.py[line:145]: userId=6222018371410468864,mobile=01634691861,token=b42ae83b68231d2e365fded2fe0e6401 登录成功
INFO - 2021-10-20 09:04:22,597 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:04:22,644 - new_apply_order.py[line:223]: 联系人信息提交成功！
INFO - 2021-10-20 09:04:22,839 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:04:22,857 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:04:22,871 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:04:23,130 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:04:23,167 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:04:24,067 - new_apply_order.py[line:510]: bvn和银行卡绑卡认证通过！
INFO - 2021-10-20 09:04:24,384 - new_apply_order.py[line:561]: user更新1条
INFO - 2021-10-20 09:04:24,557 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:04:25,598 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:04:25,961 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:04:25,999 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:04:26,786 - new_apply_order.py[line:669]: 获取token成功！token=bearer 0c58ac73-b149-444c-8e04-0ef7d2554aee！
INFO - 2021-10-20 09:04:27,132 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:04:27,379 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:04:27,390 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:04:27,402 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:04:28,754 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:04:28,768 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:04:28,774 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:04:29,083 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:04:30,100 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:30,100 - new_apply_order.py[line:802]: {'app': 'borrowme', 'loan_order_id': '1450628929024561152', 'mobile': '01634691861', 'order_status': 35}
INFO - 2021-10-20 09:04:30,611 - new_apply_order.py[line:905]: 校验重试查询第2次
ERROR - 2021-10-20 09:04:31,628 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:31,628 - new_apply_order.py[line:802]: {'app': 'borrowme', 'loan_order_id': '1450628929024561152', 'mobile': '01634691861', 'order_status': 35}
INFO - 2021-10-20 09:04:32,138 - new_apply_order.py[line:905]: 校验重试查询第3次
ERROR - 2021-10-20 09:04:33,155 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:33,155 - new_apply_order.py[line:802]: {'app': 'borrowme', 'loan_order_id': '1450628929024561152', 'mobile': '01634691861', 'order_status': 35}
INFO - 2021-10-20 09:04:33,666 - new_apply_order.py[line:905]: 校验重试查询第4次
ERROR - 2021-10-20 09:04:34,684 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:34,684 - new_apply_order.py[line:802]: {'app': 'borrowme', 'loan_order_id': '1450628929024561152', 'mobile': '01634691861', 'order_status': 35}
INFO - 2021-10-20 09:04:35,190 - new_apply_order.py[line:905]: 校验重试查询第5次
ERROR - 2021-10-20 09:04:36,211 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:36,211 - new_apply_order.py[line:802]: {'app': 'borrowme', 'loan_order_id': '1450628929024561152', 'mobile': '01634691861', 'order_status': 35}
INFO - 2021-10-20 09:04:36,718 - new_apply_order.py[line:905]: 校验重试查询第6次
ERROR - 2021-10-20 09:04:37,737 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是36
INFO - 2021-10-20 09:04:37,737 - new_apply_order.py[line:802]: {'app': 'borrowme', 'loan_order_id': '1450628929024561152', 'mobile': '01634691861', 'order_status': 36}
INFO - 2021-10-20 09:04:37,738 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:04:37,738 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时15.75s=====
INFO - 2021-10-20 09:04:37,742 - new_apply_order.py[line:882]: 开始第 moremoney【1】次进件……
INFO - 2021-10-20 09:04:37,744 - new_apply_order.py[line:84]: ======【nga测试环境】生成手机号：01634691877 ======
INFO - 2021-10-20 09:04:38,091 - new_apply_order.py[line:97]: 01634691877 检测用户存在成功！
INFO - 2021-10-20 09:04:38,135 - new_apply_order.py[line:106]: 01634691877 短信发送成功！
INFO - 2021-10-20 09:04:38,178 - new_apply_order.py[line:119]: 01634691877 注册成功！
INFO - 2021-10-20 09:04:38,238 - new_apply_order.py[line:135]: 01634691877 登录短信发送成功！
INFO - 2021-10-20 09:04:38,285 - new_apply_order.py[line:145]: userId=6222018437433008128,mobile=01634691877,token=1adfb0c845657b318f38443547d0d0ad 登录成功
INFO - 2021-10-20 09:04:38,349 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:04:38,395 - new_apply_order.py[line:223]: 联系人信息提交成功！
INFO - 2021-10-20 09:04:38,605 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:04:38,630 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:04:38,646 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:04:38,901 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:04:38,934 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:04:39,799 - new_apply_order.py[line:510]: bvn和银行卡绑卡认证通过！
INFO - 2021-10-20 09:04:40,097 - new_apply_order.py[line:561]: user更新1条
INFO - 2021-10-20 09:04:40,302 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:04:41,340 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:04:41,694 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:04:41,729 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:04:42,517 - new_apply_order.py[line:669]: 获取token成功！token=bearer 0c58ac73-b149-444c-8e04-0ef7d2554aee！
INFO - 2021-10-20 09:04:42,874 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:04:43,172 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:04:43,185 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:04:43,199 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:04:44,559 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:04:44,573 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:04:44,580 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:04:44,889 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:04:45,902 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:45,902 - new_apply_order.py[line:802]: {'app': 'moremoney', 'loan_order_id': '1450628995009351680', 'mobile': '01634691877', 'order_status': 35}
INFO - 2021-10-20 09:04:46,411 - new_apply_order.py[line:905]: 校验重试查询第2次
ERROR - 2021-10-20 09:04:47,426 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:47,427 - new_apply_order.py[line:802]: {'app': 'moremoney', 'loan_order_id': '1450628995009351680', 'mobile': '01634691877', 'order_status': 35}
INFO - 2021-10-20 09:04:47,936 - new_apply_order.py[line:905]: 校验重试查询第3次
ERROR - 2021-10-20 09:04:48,949 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:48,949 - new_apply_order.py[line:802]: {'app': 'moremoney', 'loan_order_id': '1450628995009351680', 'mobile': '01634691877', 'order_status': 35}
INFO - 2021-10-20 09:04:49,457 - new_apply_order.py[line:905]: 校验重试查询第4次
ERROR - 2021-10-20 09:04:50,472 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:50,472 - new_apply_order.py[line:802]: {'app': 'moremoney', 'loan_order_id': '1450628995009351680', 'mobile': '01634691877', 'order_status': 35}
INFO - 2021-10-20 09:04:50,981 - new_apply_order.py[line:905]: 校验重试查询第5次
ERROR - 2021-10-20 09:04:51,991 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:04:51,991 - new_apply_order.py[line:802]: {'app': 'moremoney', 'loan_order_id': '1450628995009351680', 'mobile': '01634691877', 'order_status': 35}
INFO - 2021-10-20 09:04:52,499 - new_apply_order.py[line:905]: 校验重试查询第6次
ERROR - 2021-10-20 09:04:53,514 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是36
INFO - 2021-10-20 09:04:53,515 - new_apply_order.py[line:802]: {'app': 'moremoney', 'loan_order_id': '1450628995009351680', 'mobile': '01634691877', 'order_status': 36}
INFO - 2021-10-20 09:04:53,516 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:04:53,517 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时15.77s=====
INFO - 2021-10-20 09:04:53,521 - new_apply_order.py[line:882]: 开始第 creditnaira【1】次进件……
INFO - 2021-10-20 09:04:53,522 - new_apply_order.py[line:84]: ======【nga测试环境】生成手机号：01634691893 ======
INFO - 2021-10-20 09:04:53,876 - new_apply_order.py[line:97]: 01634691893 检测用户存在成功！
INFO - 2021-10-20 09:04:53,927 - new_apply_order.py[line:106]: 01634691893 短信发送成功！
INFO - 2021-10-20 09:04:53,963 - new_apply_order.py[line:119]: 01634691893 注册成功！
INFO - 2021-10-20 09:04:54,016 - new_apply_order.py[line:135]: 01634691893 登录短信发送成功！
INFO - 2021-10-20 09:04:54,057 - new_apply_order.py[line:145]: userId=6222018503669456896,mobile=01634691893,token=2a57c4796797f826205563ba47341dac 登录成功
INFO - 2021-10-20 09:04:54,125 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:04:54,174 - new_apply_order.py[line:223]: 联系人信息提交成功！
INFO - 2021-10-20 09:04:54,368 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:04:54,389 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:04:54,403 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:04:54,724 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:04:54,754 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:04:55,785 - new_apply_order.py[line:510]: bvn和银行卡绑卡认证通过！
INFO - 2021-10-20 09:04:56,103 - new_apply_order.py[line:561]: user更新1条
INFO - 2021-10-20 09:04:56,272 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:04:57,309 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:04:57,662 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:04:57,698 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:04:58,497 - new_apply_order.py[line:669]: 获取token成功！token=bearer 0c58ac73-b149-444c-8e04-0ef7d2554aee！
INFO - 2021-10-20 09:04:58,839 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:04:59,177 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:04:59,191 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:04:59,207 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:05:00,552 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:05:00,569 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:05:00,574 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:05:00,882 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:05:01,897 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:01,898 - new_apply_order.py[line:802]: {'app': 'creditnaira', 'loan_order_id': '1450629061258383360', 'mobile': '01634691893', 'order_status': 35}
INFO - 2021-10-20 09:05:02,406 - new_apply_order.py[line:905]: 校验重试查询第2次
ERROR - 2021-10-20 09:05:03,424 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:03,424 - new_apply_order.py[line:802]: {'app': 'creditnaira', 'loan_order_id': '1450629061258383360', 'mobile': '01634691893', 'order_status': 35}
INFO - 2021-10-20 09:05:03,933 - new_apply_order.py[line:905]: 校验重试查询第3次
ERROR - 2021-10-20 09:05:04,949 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:04,949 - new_apply_order.py[line:802]: {'app': 'creditnaira', 'loan_order_id': '1450629061258383360', 'mobile': '01634691893', 'order_status': 35}
INFO - 2021-10-20 09:05:05,456 - new_apply_order.py[line:905]: 校验重试查询第4次
ERROR - 2021-10-20 09:05:06,471 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:06,471 - new_apply_order.py[line:802]: {'app': 'creditnaira', 'loan_order_id': '1450629061258383360', 'mobile': '01634691893', 'order_status': 35}
INFO - 2021-10-20 09:05:06,980 - new_apply_order.py[line:905]: 校验重试查询第5次
ERROR - 2021-10-20 09:05:07,998 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:07,998 - new_apply_order.py[line:802]: {'app': 'creditnaira', 'loan_order_id': '1450629061258383360', 'mobile': '01634691893', 'order_status': 35}
INFO - 2021-10-20 09:05:08,505 - new_apply_order.py[line:905]: 校验重试查询第6次
ERROR - 2021-10-20 09:05:09,521 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是36
INFO - 2021-10-20 09:05:09,522 - new_apply_order.py[line:802]: {'app': 'creditnaira', 'loan_order_id': '1450629061258383360', 'mobile': '01634691893', 'order_status': 36}
INFO - 2021-10-20 09:05:09,522 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:05:09,522 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时16.00s=====
INFO - 2021-10-20 09:05:09,526 - new_apply_order.py[line:882]: 开始第 inaira【1】次进件……
INFO - 2021-10-20 09:05:09,527 - new_apply_order.py[line:84]: ======【nga测试环境】生成手机号：01634691909 ======
INFO - 2021-10-20 09:05:09,874 - new_apply_order.py[line:97]: 01634691909 检测用户存在成功！
INFO - 2021-10-20 09:05:09,939 - new_apply_order.py[line:106]: 01634691909 短信发送成功！
INFO - 2021-10-20 09:05:09,988 - new_apply_order.py[line:119]: 01634691909 注册成功！
INFO - 2021-10-20 09:05:10,048 - new_apply_order.py[line:135]: 01634691909 登录短信发送成功！
INFO - 2021-10-20 09:05:10,087 - new_apply_order.py[line:145]: userId=6222018570828652544,mobile=01634691909,token=04d6634489477d8e47910561ea5ddbe1 登录成功
INFO - 2021-10-20 09:05:10,156 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:05:10,206 - new_apply_order.py[line:223]: 联系人信息提交成功！
INFO - 2021-10-20 09:05:10,484 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:05:10,504 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:05:10,520 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:05:10,783 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:05:10,814 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:05:11,758 - new_apply_order.py[line:510]: bvn和银行卡绑卡认证通过！
INFO - 2021-10-20 09:05:12,062 - new_apply_order.py[line:561]: user更新1条
INFO - 2021-10-20 09:05:12,322 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:05:13,352 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:05:13,718 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:05:13,752 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:05:14,522 - new_apply_order.py[line:669]: 获取token成功！token=bearer 0c58ac73-b149-444c-8e04-0ef7d2554aee！
INFO - 2021-10-20 09:05:14,864 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:05:15,164 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:05:15,175 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:05:15,187 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:05:16,537 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:05:16,556 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:05:16,562 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:05:16,867 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:05:17,885 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:17,885 - new_apply_order.py[line:802]: {'app': 'inaira', 'loan_order_id': '1450629128434356224', 'mobile': '01634691909', 'order_status': 35}
INFO - 2021-10-20 09:05:18,396 - new_apply_order.py[line:905]: 校验重试查询第2次
ERROR - 2021-10-20 09:05:19,412 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:19,412 - new_apply_order.py[line:802]: {'app': 'inaira', 'loan_order_id': '1450629128434356224', 'mobile': '01634691909', 'order_status': 35}
INFO - 2021-10-20 09:05:19,924 - new_apply_order.py[line:905]: 校验重试查询第3次
ERROR - 2021-10-20 09:05:20,935 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:20,935 - new_apply_order.py[line:802]: {'app': 'inaira', 'loan_order_id': '1450629128434356224', 'mobile': '01634691909', 'order_status': 35}
INFO - 2021-10-20 09:05:21,445 - new_apply_order.py[line:905]: 校验重试查询第4次
ERROR - 2021-10-20 09:05:22,461 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:22,462 - new_apply_order.py[line:802]: {'app': 'inaira', 'loan_order_id': '1450629128434356224', 'mobile': '01634691909', 'order_status': 35}
INFO - 2021-10-20 09:05:22,970 - new_apply_order.py[line:905]: 校验重试查询第5次
ERROR - 2021-10-20 09:05:23,988 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:23,988 - new_apply_order.py[line:802]: {'app': 'inaira', 'loan_order_id': '1450629128434356224', 'mobile': '01634691909', 'order_status': 35}
INFO - 2021-10-20 09:05:24,495 - new_apply_order.py[line:905]: 校验重试查询第6次
ERROR - 2021-10-20 09:05:25,511 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是36
INFO - 2021-10-20 09:05:25,511 - new_apply_order.py[line:802]: {'app': 'inaira', 'loan_order_id': '1450629128434356224', 'mobile': '01634691909', 'order_status': 36}
INFO - 2021-10-20 09:05:25,512 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:05:25,512 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时15.99s=====
INFO - 2021-10-20 09:05:25,516 - new_apply_order.py[line:882]: 开始第 runcash【1】次进件……
INFO - 2021-10-20 09:05:25,517 - new_apply_order.py[line:84]: ======【nga测试环境】生成手机号：01634691925 ======
INFO - 2021-10-20 09:05:25,875 - new_apply_order.py[line:97]: 01634691925 检测用户存在成功！
INFO - 2021-10-20 09:05:25,915 - new_apply_order.py[line:106]: 01634691925 短信发送成功！
INFO - 2021-10-20 09:05:25,949 - new_apply_order.py[line:119]: 01634691925 注册成功！
INFO - 2021-10-20 09:05:25,996 - new_apply_order.py[line:135]: 01634691925 登录短信发送成功！
INFO - 2021-10-20 09:05:26,035 - new_apply_order.py[line:145]: userId=6222018637828464640,mobile=01634691925,token=b3f6706a4797bc41e24bc70089830097 登录成功
INFO - 2021-10-20 09:05:26,095 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:05:26,142 - new_apply_order.py[line:223]: 联系人信息提交成功！
INFO - 2021-10-20 09:05:26,318 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:05:26,336 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:05:26,349 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:05:26,622 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:05:26,657 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:05:27,656 - new_apply_order.py[line:510]: bvn和银行卡绑卡认证通过！
INFO - 2021-10-20 09:05:27,965 - new_apply_order.py[line:561]: user更新1条
INFO - 2021-10-20 09:05:28,143 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:05:29,184 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:05:29,533 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:05:29,570 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:05:30,375 - new_apply_order.py[line:669]: 获取token成功！token=bearer 0c58ac73-b149-444c-8e04-0ef7d2554aee！
INFO - 2021-10-20 09:05:30,721 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:05:31,033 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:05:31,043 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:05:31,053 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:05:32,401 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:05:32,418 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:05:32,425 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:05:32,732 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:05:33,749 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:33,749 - new_apply_order.py[line:802]: {'app': 'runcash', 'loan_order_id': '1450629195283173376', 'mobile': '01634691925', 'order_status': 35}
INFO - 2021-10-20 09:05:34,259 - new_apply_order.py[line:905]: 校验重试查询第2次
ERROR - 2021-10-20 09:05:35,277 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:35,278 - new_apply_order.py[line:802]: {'app': 'runcash', 'loan_order_id': '1450629195283173376', 'mobile': '01634691925', 'order_status': 35}
INFO - 2021-10-20 09:05:35,786 - new_apply_order.py[line:905]: 校验重试查询第3次
ERROR - 2021-10-20 09:05:36,803 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:36,803 - new_apply_order.py[line:802]: {'app': 'runcash', 'loan_order_id': '1450629195283173376', 'mobile': '01634691925', 'order_status': 35}
INFO - 2021-10-20 09:05:37,313 - new_apply_order.py[line:905]: 校验重试查询第4次
ERROR - 2021-10-20 09:05:38,331 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:38,332 - new_apply_order.py[line:802]: {'app': 'runcash', 'loan_order_id': '1450629195283173376', 'mobile': '01634691925', 'order_status': 35}
INFO - 2021-10-20 09:05:38,842 - new_apply_order.py[line:905]: 校验重试查询第5次
ERROR - 2021-10-20 09:05:39,856 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:39,857 - new_apply_order.py[line:802]: {'app': 'runcash', 'loan_order_id': '1450629195283173376', 'mobile': '01634691925', 'order_status': 35}
INFO - 2021-10-20 09:05:40,363 - new_apply_order.py[line:905]: 校验重试查询第6次
ERROR - 2021-10-20 09:05:41,380 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是36
INFO - 2021-10-20 09:05:41,380 - new_apply_order.py[line:802]: {'app': 'runcash', 'loan_order_id': '1450629195283173376', 'mobile': '01634691925', 'order_status': 36}
INFO - 2021-10-20 09:05:41,381 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:05:41,381 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时15.87s=====
INFO - 2021-10-20 09:05:41,386 - new_apply_order.py[line:882]: 开始第 formoney【1】次进件……
INFO - 2021-10-20 09:05:41,387 - new_apply_order.py[line:84]: ======【nga测试环境】生成手机号：01634691941 ======
INFO - 2021-10-20 09:05:41,741 - new_apply_order.py[line:97]: 01634691941 检测用户存在成功！
INFO - 2021-10-20 09:05:41,791 - new_apply_order.py[line:106]: 01634691941 短信发送成功！
INFO - 2021-10-20 09:05:41,833 - new_apply_order.py[line:119]: 01634691941 注册成功！
INFO - 2021-10-20 09:05:41,921 - new_apply_order.py[line:135]: 01634691941 登录短信发送成功！
INFO - 2021-10-20 09:05:41,967 - new_apply_order.py[line:145]: userId=6222018704421429248,mobile=01634691941,token=6a5ee6b8d315ed165523fe80582dbac8 登录成功
INFO - 2021-10-20 09:05:42,031 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:05:42,079 - new_apply_order.py[line:223]: 联系人信息提交成功！
INFO - 2021-10-20 09:05:42,358 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:05:42,375 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:05:42,386 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:05:42,661 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:05:42,689 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:05:43,592 - new_apply_order.py[line:510]: bvn和银行卡绑卡认证通过！
INFO - 2021-10-20 09:05:43,898 - new_apply_order.py[line:561]: user更新1条
INFO - 2021-10-20 09:05:44,117 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:05:45,156 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:05:45,509 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:05:45,549 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:05:46,276 - new_apply_order.py[line:669]: 获取token成功！token=bearer 0c58ac73-b149-444c-8e04-0ef7d2554aee！
INFO - 2021-10-20 09:05:46,620 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:05:46,920 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:05:46,933 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:05:46,945 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:05:48,314 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:05:48,332 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:05:48,339 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:05:48,645 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:05:49,658 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:49,658 - new_apply_order.py[line:802]: {'app': 'formoney', 'loan_order_id': '1450629262249431040', 'mobile': '01634691941', 'order_status': 35}
INFO - 2021-10-20 09:05:50,168 - new_apply_order.py[line:905]: 校验重试查询第2次
ERROR - 2021-10-20 09:05:51,186 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:51,187 - new_apply_order.py[line:802]: {'app': 'formoney', 'loan_order_id': '1450629262249431040', 'mobile': '01634691941', 'order_status': 35}
INFO - 2021-10-20 09:05:51,695 - new_apply_order.py[line:905]: 校验重试查询第3次
ERROR - 2021-10-20 09:05:52,710 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:52,710 - new_apply_order.py[line:802]: {'app': 'formoney', 'loan_order_id': '1450629262249431040', 'mobile': '01634691941', 'order_status': 35}
INFO - 2021-10-20 09:05:53,217 - new_apply_order.py[line:905]: 校验重试查询第4次
ERROR - 2021-10-20 09:05:54,233 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:54,233 - new_apply_order.py[line:802]: {'app': 'formoney', 'loan_order_id': '1450629262249431040', 'mobile': '01634691941', 'order_status': 35}
INFO - 2021-10-20 09:05:54,742 - new_apply_order.py[line:905]: 校验重试查询第5次
ERROR - 2021-10-20 09:05:55,755 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:05:55,755 - new_apply_order.py[line:802]: {'app': 'formoney', 'loan_order_id': '1450629262249431040', 'mobile': '01634691941', 'order_status': 35}
INFO - 2021-10-20 09:05:56,262 - new_apply_order.py[line:905]: 校验重试查询第6次
ERROR - 2021-10-20 09:05:57,275 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是36
INFO - 2021-10-20 09:05:57,275 - new_apply_order.py[line:802]: {'app': 'formoney', 'loan_order_id': '1450629262249431040', 'mobile': '01634691941', 'order_status': 36}
INFO - 2021-10-20 09:05:57,276 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:05:57,276 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时15.89s=====
INFO - 2021-10-20 09:05:57,283 - new_apply_order.py[line:882]: 开始第 Gotocash【1】次进件……
INFO - 2021-10-20 09:05:57,284 - new_apply_order.py[line:84]: ======【nga测试环境】生成手机号：01634691957 ======
INFO - 2021-10-20 09:05:57,634 - new_apply_order.py[line:97]: 01634691957 检测用户存在成功！
INFO - 2021-10-20 09:05:57,683 - new_apply_order.py[line:106]: 01634691957 短信发送成功！
INFO - 2021-10-20 09:05:57,720 - new_apply_order.py[line:119]: 01634691957 注册成功！
INFO - 2021-10-20 09:05:57,771 - new_apply_order.py[line:135]: 01634691957 登录短信发送成功！
INFO - 2021-10-20 09:05:57,813 - new_apply_order.py[line:145]: userId=6222018771085697024,mobile=01634691957,token=fda0baeb524fbeb002eeff92dce5e2c9 登录成功
INFO - 2021-10-20 09:05:57,874 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:05:57,920 - new_apply_order.py[line:223]: 联系人信息提交成功！
INFO - 2021-10-20 09:05:58,096 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:05:58,112 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:05:58,127 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:05:58,383 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:05:58,421 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:05:59,416 - new_apply_order.py[line:510]: bvn和银行卡绑卡认证通过！
INFO - 2021-10-20 09:05:59,745 - new_apply_order.py[line:561]: user更新1条
INFO - 2021-10-20 09:05:59,929 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:06:00,972 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:06:01,322 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:06:01,363 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:06:02,143 - new_apply_order.py[line:669]: 获取token成功！token=bearer 0c58ac73-b149-444c-8e04-0ef7d2554aee！
INFO - 2021-10-20 09:06:02,486 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:06:02,788 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:06:02,800 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:06:02,811 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:06:04,161 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:06:04,181 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:06:04,189 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:06:04,494 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:06:05,509 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:06:05,510 - new_apply_order.py[line:802]: {'app': 'Gotocash', 'loan_order_id': '1450629328590737408', 'mobile': '01634691957', 'order_status': 35}
INFO - 2021-10-20 09:06:06,017 - new_apply_order.py[line:905]: 校验重试查询第2次
ERROR - 2021-10-20 09:06:07,031 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:06:07,031 - new_apply_order.py[line:802]: {'app': 'Gotocash', 'loan_order_id': '1450629328590737408', 'mobile': '01634691957', 'order_status': 35}
INFO - 2021-10-20 09:06:07,539 - new_apply_order.py[line:905]: 校验重试查询第3次
ERROR - 2021-10-20 09:06:08,556 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:06:08,556 - new_apply_order.py[line:802]: {'app': 'Gotocash', 'loan_order_id': '1450629328590737408', 'mobile': '01634691957', 'order_status': 35}
INFO - 2021-10-20 09:06:09,066 - new_apply_order.py[line:905]: 校验重试查询第4次
ERROR - 2021-10-20 09:06:10,083 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:06:10,084 - new_apply_order.py[line:802]: {'app': 'Gotocash', 'loan_order_id': '1450629328590737408', 'mobile': '01634691957', 'order_status': 35}
INFO - 2021-10-20 09:06:10,590 - new_apply_order.py[line:905]: 校验重试查询第5次
ERROR - 2021-10-20 09:06:11,605 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:06:11,605 - new_apply_order.py[line:802]: {'app': 'Gotocash', 'loan_order_id': '1450629328590737408', 'mobile': '01634691957', 'order_status': 35}
INFO - 2021-10-20 09:06:12,112 - new_apply_order.py[line:905]: 校验重试查询第6次
ERROR - 2021-10-20 09:06:13,128 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是36
INFO - 2021-10-20 09:06:13,129 - new_apply_order.py[line:802]: {'app': 'Gotocash', 'loan_order_id': '1450629328590737408', 'mobile': '01634691957', 'order_status': 36}
INFO - 2021-10-20 09:06:13,129 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:06:13,129 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时15.85s=====
INFO - 2021-10-20 09:06:13,134 - new_apply_order.py[line:882]: 开始第 Gotcash【1】次进件……
INFO - 2021-10-20 09:06:13,136 - new_apply_order.py[line:84]: ======【nga测试环境】生成手机号：01634691973 ======
INFO - 2021-10-20 09:06:13,501 - new_apply_order.py[line:97]: 01634691973 检测用户存在成功！
INFO - 2021-10-20 09:06:13,555 - new_apply_order.py[line:106]: 01634691973 短信发送成功！
INFO - 2021-10-20 09:06:13,594 - new_apply_order.py[line:119]: 01634691973 注册成功！
INFO - 2021-10-20 09:06:13,655 - new_apply_order.py[line:135]: 01634691973 登录短信发送成功！
INFO - 2021-10-20 09:06:13,697 - new_apply_order.py[line:145]: userId=6222018837653495808,mobile=01634691973,token=4c6429bcacac6f2ca1ea2a4f40bfed02 登录成功
INFO - 2021-10-20 09:06:13,766 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:06:13,813 - new_apply_order.py[line:223]: 联系人信息提交成功！
INFO - 2021-10-20 09:06:14,085 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:06:14,106 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:06:14,122 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:06:14,395 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:06:14,430 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:06:15,327 - new_apply_order.py[line:510]: bvn和银行卡绑卡认证通过！
INFO - 2021-10-20 09:06:15,653 - new_apply_order.py[line:561]: user更新1条
INFO - 2021-10-20 09:06:15,850 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:06:16,890 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:06:17,267 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:06:17,307 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:06:18,110 - new_apply_order.py[line:669]: 获取token成功！token=bearer 0c58ac73-b149-444c-8e04-0ef7d2554aee！
INFO - 2021-10-20 09:06:18,456 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:06:18,785 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:06:18,798 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:06:18,810 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:06:20,184 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:06:20,204 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:06:20,211 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:06:20,521 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:06:21,540 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:06:21,540 - new_apply_order.py[line:802]: {'app': 'Gotcash', 'loan_order_id': '1450629395355668480', 'mobile': '01634691973', 'order_status': 35}
INFO - 2021-10-20 09:06:22,049 - new_apply_order.py[line:905]: 校验重试查询第2次
INFO - 2021-10-20 09:06:23,063 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-10-20 09:06:23,064 - new_apply_order.py[line:802]: {'app': 'Gotcash', 'loan_order_id': '1450629395355668480', 'mobile': '01634691973', 'order_status': 40}
INFO - 2021-10-20 09:06:23,065 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:06:23,065 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时9.93s=====
INFO - 2021-10-20 09:06:23,068 - new_apply_order.py[line:882]: 开始第 faircash【1】次进件……
INFO - 2021-10-20 09:06:23,070 - new_apply_order.py[line:84]: ======【nga测试环境】生成手机号：01634691983 ======
INFO - 2021-10-20 09:06:23,419 - new_apply_order.py[line:97]: 01634691983 检测用户存在成功！
INFO - 2021-10-20 09:06:23,476 - new_apply_order.py[line:106]: 01634691983 短信发送成功！
INFO - 2021-10-20 09:06:23,513 - new_apply_order.py[line:119]: 01634691983 注册成功！
INFO - 2021-10-20 09:06:23,569 - new_apply_order.py[line:135]: 01634691983 登录短信发送成功！
INFO - 2021-10-20 09:06:23,612 - new_apply_order.py[line:145]: userId=6222018879273574400,mobile=01634691983,token=f266b2ff9f3242b578398d07a40c49b2 登录成功
INFO - 2021-10-20 09:06:23,669 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:06:23,712 - new_apply_order.py[line:223]: 联系人信息提交成功！
INFO - 2021-10-20 09:06:23,890 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:06:23,908 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:06:23,920 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:06:24,211 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:06:24,247 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:06:25,274 - new_apply_order.py[line:510]: bvn和银行卡绑卡认证通过！
INFO - 2021-10-20 09:06:25,582 - new_apply_order.py[line:561]: user更新1条
INFO - 2021-10-20 09:06:25,754 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:06:26,794 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:06:27,151 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:06:27,190 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:06:27,986 - new_apply_order.py[line:669]: 获取token成功！token=bearer 0c58ac73-b149-444c-8e04-0ef7d2554aee！
INFO - 2021-10-20 09:06:28,334 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:06:28,652 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:06:28,665 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:06:28,676 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:06:30,028 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:06:30,040 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:06:30,045 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:06:30,354 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:06:31,371 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:06:31,371 - new_apply_order.py[line:802]: {'app': 'faircash', 'loan_order_id': '1450629436757643264', 'mobile': '01634691983', 'order_status': 35}
INFO - 2021-10-20 09:06:31,880 - new_apply_order.py[line:905]: 校验重试查询第2次
INFO - 2021-10-20 09:06:32,894 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-10-20 09:06:32,894 - new_apply_order.py[line:802]: {'app': 'faircash', 'loan_order_id': '1450629436757643264', 'mobile': '01634691983', 'order_status': 40}
INFO - 2021-10-20 09:06:32,895 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:06:32,895 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时9.83s=====
INFO - 2021-10-20 09:06:32,900 - new_apply_order.py[line:882]: 开始第 pickcredit【1】次进件……
INFO - 2021-10-20 09:06:32,901 - new_apply_order.py[line:84]: ======【nga测试环境】生成手机号：01634691992 ======
INFO - 2021-10-20 09:06:33,244 - new_apply_order.py[line:97]: 01634691992 检测用户存在成功！
INFO - 2021-10-20 09:06:33,297 - new_apply_order.py[line:106]: 01634691992 短信发送成功！
INFO - 2021-10-20 09:06:33,336 - new_apply_order.py[line:119]: 01634691992 注册成功！
INFO - 2021-10-20 09:06:33,397 - new_apply_order.py[line:135]: 01634691992 登录短信发送成功！
INFO - 2021-10-20 09:06:33,447 - new_apply_order.py[line:145]: userId=6222018920461639680,mobile=01634691992,token=b74e4b17720a018e1731eec1a87bcb0b 登录成功
INFO - 2021-10-20 09:06:33,508 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:06:33,553 - new_apply_order.py[line:223]: 联系人信息提交成功！
INFO - 2021-10-20 09:06:33,723 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:06:33,739 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:06:33,757 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:06:34,037 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:06:34,067 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:06:35,112 - new_apply_order.py[line:510]: bvn和银行卡绑卡认证通过！
INFO - 2021-10-20 09:06:35,434 - new_apply_order.py[line:561]: user更新1条
INFO - 2021-10-20 09:06:35,661 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:06:36,690 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:06:37,044 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:06:37,085 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:06:37,888 - new_apply_order.py[line:669]: 获取token成功！token=bearer 0c58ac73-b149-444c-8e04-0ef7d2554aee！
INFO - 2021-10-20 09:06:38,229 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:06:38,542 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:06:38,551 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:06:38,561 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:06:39,919 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:06:39,939 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:06:39,947 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:06:40,261 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:06:41,276 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:06:41,277 - new_apply_order.py[line:802]: {'app': 'pickcredit', 'loan_order_id': '1450629477966680064', 'mobile': '01634691992', 'order_status': 35}
INFO - 2021-10-20 09:06:41,791 - new_apply_order.py[line:905]: 校验重试查询第2次
ERROR - 2021-10-20 09:06:42,804 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:06:42,804 - new_apply_order.py[line:802]: {'app': 'pickcredit', 'loan_order_id': '1450629477966680064', 'mobile': '01634691992', 'order_status': 35}
INFO - 2021-10-20 09:06:43,313 - new_apply_order.py[line:905]: 校验重试查询第3次
ERROR - 2021-10-20 09:06:44,332 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:06:44,332 - new_apply_order.py[line:802]: {'app': 'pickcredit', 'loan_order_id': '1450629477966680064', 'mobile': '01634691992', 'order_status': 35}
INFO - 2021-10-20 09:06:44,844 - new_apply_order.py[line:905]: 校验重试查询第4次
ERROR - 2021-10-20 09:06:45,861 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:06:45,861 - new_apply_order.py[line:802]: {'app': 'pickcredit', 'loan_order_id': '1450629477966680064', 'mobile': '01634691992', 'order_status': 35}
INFO - 2021-10-20 09:06:46,377 - new_apply_order.py[line:905]: 校验重试查询第5次
ERROR - 2021-10-20 09:06:47,397 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是36
INFO - 2021-10-20 09:06:47,398 - new_apply_order.py[line:802]: {'app': 'pickcredit', 'loan_order_id': '1450629477966680064', 'mobile': '01634691992', 'order_status': 36}
INFO - 2021-10-20 09:06:47,398 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:06:47,399 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时14.50s=====
INFO - 2021-10-20 09:06:47,402 - new_apply_order.py[line:882]: 开始第 pickcash【1】次进件……
INFO - 2021-10-20 09:06:47,403 - new_apply_order.py[line:84]: ======【nga测试环境】生成手机号：01634692007 ======
INFO - 2021-10-20 09:06:47,771 - new_apply_order.py[line:97]: 01634692007 检测用户存在成功！
INFO - 2021-10-20 09:06:47,822 - new_apply_order.py[line:106]: 01634692007 短信发送成功！
INFO - 2021-10-20 09:06:47,859 - new_apply_order.py[line:119]: 01634692007 注册成功！
INFO - 2021-10-20 09:06:47,925 - new_apply_order.py[line:135]: 01634692007 登录短信发送成功！
INFO - 2021-10-20 09:06:47,981 - new_apply_order.py[line:145]: userId=6222018981371322368,mobile=01634692007,token=fea2fe91027f45b5615a58c5bd3123e8 登录成功
INFO - 2021-10-20 09:06:48,053 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:06:48,107 - new_apply_order.py[line:223]: 联系人信息提交成功！
INFO - 2021-10-20 09:06:48,384 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:06:48,401 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:06:48,417 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:06:48,723 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:06:48,780 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:06:49,794 - new_apply_order.py[line:510]: bvn和银行卡绑卡认证通过！
INFO - 2021-10-20 09:06:50,116 - new_apply_order.py[line:561]: user更新1条
INFO - 2021-10-20 09:06:50,344 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:06:51,388 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:06:51,751 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:06:51,787 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:06:52,563 - new_apply_order.py[line:669]: 获取token成功！token=bearer 0c58ac73-b149-444c-8e04-0ef7d2554aee！
INFO - 2021-10-20 09:06:52,917 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:06:53,207 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:06:53,219 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:06:53,230 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:06:54,595 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:06:54,612 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:06:54,617 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:06:54,926 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:06:55,949 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:06:55,950 - new_apply_order.py[line:802]: {'app': 'pickcash', 'loan_order_id': '1450629539190935552', 'mobile': '01634692007', 'order_status': 35}
INFO - 2021-10-20 09:06:56,457 - new_apply_order.py[line:905]: 校验重试查询第2次
ERROR - 2021-10-20 09:06:57,474 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:06:57,475 - new_apply_order.py[line:802]: {'app': 'pickcash', 'loan_order_id': '1450629539190935552', 'mobile': '01634692007', 'order_status': 35}
INFO - 2021-10-20 09:06:57,983 - new_apply_order.py[line:905]: 校验重试查询第3次
ERROR - 2021-10-20 09:06:59,006 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:06:59,006 - new_apply_order.py[line:802]: {'app': 'pickcash', 'loan_order_id': '1450629539190935552', 'mobile': '01634692007', 'order_status': 35}
INFO - 2021-10-20 09:06:59,519 - new_apply_order.py[line:905]: 校验重试查询第4次
ERROR - 2021-10-20 09:07:00,537 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:07:00,537 - new_apply_order.py[line:802]: {'app': 'pickcash', 'loan_order_id': '1450629539190935552', 'mobile': '01634692007', 'order_status': 35}
INFO - 2021-10-20 09:07:01,048 - new_apply_order.py[line:905]: 校验重试查询第5次
ERROR - 2021-10-20 09:07:02,067 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是36
INFO - 2021-10-20 09:07:02,068 - new_apply_order.py[line:802]: {'app': 'pickcash', 'loan_order_id': '1450629539190935552', 'mobile': '01634692007', 'order_status': 36}
INFO - 2021-10-20 09:07:02,068 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:07:02,068 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时14.67s=====
INFO - 2021-10-20 09:07:02,072 - new_apply_order.py[line:882]: 开始第 jopay【1】次进件……
INFO - 2021-10-20 09:07:02,073 - new_apply_order.py[line:84]: ======【nga测试环境】生成手机号：01634692022 ======
INFO - 2021-10-20 09:07:02,422 - new_apply_order.py[line:97]: 01634692022 检测用户存在成功！
INFO - 2021-10-20 09:07:02,468 - new_apply_order.py[line:106]: 01634692022 短信发送成功！
INFO - 2021-10-20 09:07:02,504 - new_apply_order.py[line:119]: 01634692022 注册成功！
INFO - 2021-10-20 09:07:02,552 - new_apply_order.py[line:135]: 01634692022 登录短信发送成功！
INFO - 2021-10-20 09:07:02,591 - new_apply_order.py[line:145]: userId=6222019042813681664,mobile=01634692022,token=ec19e636e82b5abe8c26dbc4bbc13c67 登录成功
INFO - 2021-10-20 09:07:02,648 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:07:02,701 - new_apply_order.py[line:223]: 联系人信息提交成功！
INFO - 2021-10-20 09:07:02,869 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:07:02,882 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:07:02,893 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:07:03,139 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:07:03,173 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:07:04,294 - new_apply_order.py[line:510]: bvn和银行卡绑卡认证通过！
INFO - 2021-10-20 09:07:04,622 - new_apply_order.py[line:561]: user更新1条
INFO - 2021-10-20 09:07:04,795 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:07:05,837 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:07:06,182 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:06,231 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:07:07,019 - new_apply_order.py[line:669]: 获取token成功！token=bearer 0c58ac73-b149-444c-8e04-0ef7d2554aee！
INFO - 2021-10-20 09:07:07,376 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:07,713 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:07:07,726 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:07:07,738 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:07:09,096 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:09,112 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:07:09,117 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:07:09,426 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:07:10,445 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:07:10,445 - new_apply_order.py[line:802]: {'app': 'jopay', 'loan_order_id': '1450629600230641664', 'mobile': '01634692022', 'order_status': 35}
INFO - 2021-10-20 09:07:10,957 - new_apply_order.py[line:905]: 校验重试查询第2次
ERROR - 2021-10-20 09:07:11,978 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:07:11,978 - new_apply_order.py[line:802]: {'app': 'jopay', 'loan_order_id': '1450629600230641664', 'mobile': '01634692022', 'order_status': 35}
INFO - 2021-10-20 09:07:12,493 - new_apply_order.py[line:905]: 校验重试查询第3次
ERROR - 2021-10-20 09:07:13,516 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:07:13,516 - new_apply_order.py[line:802]: {'app': 'jopay', 'loan_order_id': '1450629600230641664', 'mobile': '01634692022', 'order_status': 35}
INFO - 2021-10-20 09:07:14,027 - new_apply_order.py[line:905]: 校验重试查询第4次
ERROR - 2021-10-20 09:07:15,046 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:07:15,047 - new_apply_order.py[line:802]: {'app': 'jopay', 'loan_order_id': '1450629600230641664', 'mobile': '01634692022', 'order_status': 35}
INFO - 2021-10-20 09:07:15,560 - new_apply_order.py[line:905]: 校验重试查询第5次
ERROR - 2021-10-20 09:07:16,580 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:07:16,580 - new_apply_order.py[line:802]: {'app': 'jopay', 'loan_order_id': '1450629600230641664', 'mobile': '01634692022', 'order_status': 35}
INFO - 2021-10-20 09:07:17,094 - new_apply_order.py[line:905]: 校验重试查询第6次
ERROR - 2021-10-20 09:07:18,115 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是36
INFO - 2021-10-20 09:07:18,115 - new_apply_order.py[line:802]: {'app': 'jopay', 'loan_order_id': '1450629600230641664', 'mobile': '01634692022', 'order_status': 36}
INFO - 2021-10-20 09:07:18,116 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:07:18,116 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时16.04s=====
INFO - 2021-10-20 09:07:18,121 - new_apply_order.py[line:882]: 开始第 ikash【1】次进件……
INFO - 2021-10-20 09:07:18,122 - new_apply_order.py[line:84]: ======【ke测试环境】生成手机号：734692038 ======
INFO - 2021-10-20 09:07:18,512 - new_apply_order.py[line:97]: 734692038 检测用户存在成功！
INFO - 2021-10-20 09:07:18,588 - new_apply_order.py[line:106]: 734692038 短信发送成功！
INFO - 2021-10-20 09:07:18,640 - new_apply_order.py[line:119]: 734692038 注册成功！
INFO - 2021-10-20 09:07:18,696 - new_apply_order.py[line:135]: 734692038 登录短信发送成功！
INFO - 2021-10-20 09:07:18,750 - new_apply_order.py[line:145]: userId=6222019110498213888,mobile=734692038,token=3f1c09eae30c3f6217f2a2c2e4e5ec87 登录成功
INFO - 2021-10-20 09:07:18,857 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:07:18,912 - new_apply_order.py[line:232]: 联系人信息提交成功！
INFO - 2021-10-20 09:07:19,688 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:07:19,707 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:07:19,720 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:07:20,019 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:07:20,060 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:07:20,381 - new_apply_order.py[line:577]: 绑卡成功！
INFO - 2021-10-20 09:07:20,615 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:07:21,652 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:07:22,015 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:22,201 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:07:23,033 - new_apply_order.py[line:669]: 获取token成功！token=bearer cc0555d0-e7c9-4ad7-a606-927659e0628b！
INFO - 2021-10-20 09:07:23,389 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:23,979 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:07:23,990 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:07:23,999 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:07:25,379 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:25,395 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:07:25,403 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:07:25,762 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:26,080 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-10-20 09:07:27,096 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-20 09:07:27,097 - new_apply_order.py[line:802]: {'app': 'ikash', 'loan_order_id': '1450629668349546496', 'mobile': '734692038', 'order_status': 35}
INFO - 2021-10-20 09:07:27,993 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:28,201 - new_apply_order.py[line:770]: 放款回调成功！
INFO - 2021-10-20 09:07:28,201 - new_apply_order.py[line:905]: 校验重试查询第2次
INFO - 2021-10-20 09:07:29,218 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-10-20 09:07:29,219 - new_apply_order.py[line:802]: {'app': 'ikash', 'loan_order_id': '1450629668349546496', 'mobile': '734692038', 'order_status': 40}
INFO - 2021-10-20 09:07:29,219 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:07:29,220 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时11.10s=====
INFO - 2021-10-20 09:07:29,222 - new_apply_order.py[line:882]: 开始第 kencash【1】次进件……
INFO - 2021-10-20 09:07:29,223 - new_apply_order.py[line:84]: ======【ke测试环境】生成手机号：734692049 ======
INFO - 2021-10-20 09:07:29,577 - new_apply_order.py[line:97]: 734692049 检测用户存在成功！
INFO - 2021-10-20 09:07:29,629 - new_apply_order.py[line:106]: 734692049 短信发送成功！
INFO - 2021-10-20 09:07:29,672 - new_apply_order.py[line:119]: 734692049 注册成功！
INFO - 2021-10-20 09:07:29,719 - new_apply_order.py[line:135]: 734692049 登录短信发送成功！
INFO - 2021-10-20 09:07:29,769 - new_apply_order.py[line:145]: userId=6222019156761387008,mobile=734692049,token=712e3e5a4dd2545a3aebe719ba963d7f 登录成功
INFO - 2021-10-20 09:07:29,886 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:07:29,940 - new_apply_order.py[line:232]: 联系人信息提交成功！
INFO - 2021-10-20 09:07:30,568 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:07:30,588 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:07:30,604 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:07:30,894 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:07:30,932 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:07:31,244 - new_apply_order.py[line:577]: 绑卡成功！
INFO - 2021-10-20 09:07:31,433 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:07:32,470 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:07:32,822 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:32,903 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:07:33,700 - new_apply_order.py[line:669]: 获取token成功！token=bearer cc0555d0-e7c9-4ad7-a606-927659e0628b！
INFO - 2021-10-20 09:07:34,059 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:34,359 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:07:34,372 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:07:34,383 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:07:35,738 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:35,750 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:07:35,757 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:07:36,105 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:36,315 - new_apply_order.py[line:770]: 放款回调成功！
INFO - 2021-10-20 09:07:36,625 - new_apply_order.py[line:905]: 校验重试查询第1次
INFO - 2021-10-20 09:07:37,685 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-10-20 09:07:37,685 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1450629714495279104', 'mobile': '734692049', 'order_status': 40}
INFO - 2021-10-20 09:07:37,686 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:07:37,686 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时8.46s=====
INFO - 2021-10-20 09:07:37,688 - new_apply_order.py[line:882]: 开始第 oranch【1】次进件……
INFO - 2021-10-20 09:07:37,689 - new_apply_order.py[line:84]: ======【ke测试环境】生成手机号：734692057 ======
INFO - 2021-10-20 09:07:38,057 - new_apply_order.py[line:97]: 734692057 检测用户存在成功！
INFO - 2021-10-20 09:07:38,101 - new_apply_order.py[line:106]: 734692057 短信发送成功！
INFO - 2021-10-20 09:07:38,150 - new_apply_order.py[line:119]: 734692057 注册成功！
INFO - 2021-10-20 09:07:38,219 - new_apply_order.py[line:135]: 734692057 登录短信发送成功！
INFO - 2021-10-20 09:07:38,266 - new_apply_order.py[line:145]: userId=6222019192333279232,mobile=734692057,token=d294330eaedb857fc561bbb5ba3b323f 登录成功
INFO - 2021-10-20 09:07:38,353 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:07:38,406 - new_apply_order.py[line:232]: 联系人信息提交成功！
INFO - 2021-10-20 09:07:38,767 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:07:38,785 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:07:38,827 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:07:39,122 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:07:39,159 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:07:39,493 - new_apply_order.py[line:577]: 绑卡成功！
INFO - 2021-10-20 09:07:39,701 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:07:40,742 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:07:41,098 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:41,164 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:07:41,962 - new_apply_order.py[line:669]: 获取token成功！token=bearer cc0555d0-e7c9-4ad7-a606-927659e0628b！
INFO - 2021-10-20 09:07:42,316 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:42,622 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:07:42,634 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:07:42,648 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:07:44,006 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:44,023 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:07:44,032 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:07:44,396 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:44,556 - new_apply_order.py[line:770]: 放款回调成功！
INFO - 2021-10-20 09:07:44,864 - new_apply_order.py[line:905]: 校验重试查询第1次
INFO - 2021-10-20 09:07:45,882 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-10-20 09:07:45,883 - new_apply_order.py[line:802]: {'app': 'oranch', 'loan_order_id': '1450629749995868160', 'mobile': '734692057', 'order_status': 40}
INFO - 2021-10-20 09:07:45,883 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:07:45,883 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时8.20s=====
INFO - 2021-10-20 09:07:45,885 - new_apply_order.py[line:882]: 开始第 faikash【1】次进件……
INFO - 2021-10-20 09:07:45,886 - new_apply_order.py[line:84]: ======【ke测试环境】生成手机号：734692065 ======
INFO - 2021-10-20 09:07:46,237 - new_apply_order.py[line:97]: 734692065 检测用户存在成功！
INFO - 2021-10-20 09:07:46,284 - new_apply_order.py[line:106]: 734692065 短信发送成功！
INFO - 2021-10-20 09:07:46,327 - new_apply_order.py[line:119]: 734692065 注册成功！
INFO - 2021-10-20 09:07:46,374 - new_apply_order.py[line:135]: 734692065 登录短信发送成功！
INFO - 2021-10-20 09:07:46,425 - new_apply_order.py[line:145]: userId=6222019226613325824,mobile=734692065,token=b14f7a3824ec7e5605c68b8d4b27ba90 登录成功
INFO - 2021-10-20 09:07:46,522 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-10-20 09:07:46,577 - new_apply_order.py[line:232]: 联系人信息提交成功！
INFO - 2021-10-20 09:07:46,956 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-10-20 09:07:46,973 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-20 09:07:46,988 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-10-20 09:07:47,269 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-20 09:07:47,309 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-10-20 09:07:47,606 - new_apply_order.py[line:577]: 绑卡成功！
INFO - 2021-10-20 09:07:47,793 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-20 09:07:48,837 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-10-20 09:07:49,268 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:49,337 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-10-20 09:07:50,162 - new_apply_order.py[line:669]: 获取token成功！token=bearer cc0555d0-e7c9-4ad7-a606-927659e0628b！
INFO - 2021-10-20 09:07:50,517 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:50,841 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-10-20 09:07:50,853 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-10-20 09:07:50,862 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-20 09:07:52,228 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:52,245 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-10-20 09:07:52,252 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-20 09:07:52,603 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-10-20 09:07:52,825 - new_apply_order.py[line:770]: 放款回调成功！
INFO - 2021-10-20 09:07:53,132 - new_apply_order.py[line:905]: 校验重试查询第1次
INFO - 2021-10-20 09:07:54,154 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-10-20 09:07:54,155 - new_apply_order.py[line:802]: {'app': 'faikash', 'loan_order_id': '1450629784271720448', 'mobile': '734692065', 'order_status': 40}
INFO - 2021-10-20 09:07:54,155 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-10-20 09:07:54,156 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时8.27s=====
