INFO - 2021-08-30 11:38:31,743 - new_apply_order.py[line:452]: 开始第 quickcash【1】次进件……
INFO - 2021-08-30 11:38:31,744 - new_apply_order.py[line:79]: ======【nga测试环境】生成手机号：01630294711 ======
INFO - 2021-08-30 11:38:32,108 - new_apply_order.py[line:88]: 01630294711 检测用户存在成功！
INFO - 2021-08-30 11:38:32,159 - new_apply_order.py[line:95]: 01630294711 短信发送成功！
INFO - 2021-08-30 11:38:32,200 - new_apply_order.py[line:105]: 01630294711 注册成功！
ERROR - 2021-08-30 11:38:32,231 - new_apply_order.py[line:124]: 登录失败!
ERROR - 2021-08-30 11:38:32,257 - new_apply_order.py[line:170]: 个人信息提交失败！
ERROR - 2021-08-30 11:38:32,275 - new_apply_order.py[line:179]: 联系人信息提交失败！
ERROR - 2021-08-30 11:38:32,291 - new_apply_order.py[line:196]: 创建预审失败{"code":"9001","msg":"System unknown error","data":null}
INFO - 2021-08-30 11:38:32,303 - new_apply_order.py[line:202]: 预审状态修改为通过,更新条数 0
INFO - 2021-08-30 11:38:32,311 - new_apply_order.py[line:205]: 更新初始额度！更新条数 0
ERROR - 2021-08-30 11:38:32,348 - new_apply_order.py[line:498]: 'NoneType' object is not subscriptable
ERROR - 2021-08-30 11:38:32,350 - new_apply_order.py[line:499]: None
