INFO - 2021-08-30 20:10:46,188 - new_apply_order.py[line:450]: 开始第 borrowme【1】次进件……
INFO - 2021-08-30 20:10:46,189 - new_apply_order.py[line:79]: ======【nga测试环境】生成手机号：01630325446 ======
INFO - 2021-08-30 20:10:46,566 - new_apply_order.py[line:86]: 01630325446 检测用户存在成功！
INFO - 2021-08-30 20:10:46,615 - new_apply_order.py[line:93]: 01630325446 短信发送成功！
INFO - 2021-08-30 20:10:46,653 - new_apply_order.py[line:103]: 01630325446 注册成功！
ERROR - 2021-08-30 20:10:46,678 - new_apply_order.py[line:123]: 登录失败!
ERROR - 2021-08-30 20:10:46,705 - new_apply_order.py[line:169]: 个人信息提交失败！
ERROR - 2021-08-30 20:10:46,722 - new_apply_order.py[line:178]: 联系人信息提交失败！
ERROR - 2021-08-30 20:10:46,738 - new_apply_order.py[line:195]: 创建预审失败{"code":"9001","msg":"System unknown error","data":null}
INFO - 2021-08-30 20:10:46,748 - new_apply_order.py[line:201]: 预审状态修改为通过,更新条数 0
INFO - 2021-08-30 20:10:46,755 - new_apply_order.py[line:204]: 更新初始额度！更新条数 0
ERROR - 2021-08-30 20:10:46,791 - new_apply_order.py[line:496]: 'NoneType' object is not subscriptable
ERROR - 2021-08-30 20:10:46,791 - new_apply_order.py[line:497]: None
