INFO - 2021-08-31 19:34:57,161 - new_apply_order.py[line:517]: 开始第 quickcash【1】次进件……
INFO - 2021-08-31 19:34:57,162 - new_apply_order.py[line:79]: ======【nga测试环境】生成手机号：01630409697 ======
INFO - 2021-08-31 19:34:57,544 - new_apply_order.py[line:86]: 01630409697 检测用户存在成功！
INFO - 2021-08-31 19:34:57,597 - new_apply_order.py[line:93]: 01630409697 短信发送成功！
INFO - 2021-08-31 19:34:57,637 - new_apply_order.py[line:103]: 01630409697 注册成功！
INFO - 2021-08-31 19:34:57,684 - new_apply_order.py[line:113]: 01630409697 登录短信发送成功！
INFO - 2021-08-31 19:34:57,724 - new_apply_order.py[line:121]: userId=6204057670396944384,mobile=01630409697,token=91c24c7f54a1c43080eea83a93e9b282 登录成功
INFO - 2021-08-31 19:34:57,794 - new_apply_order.py[line:172]: 个人信息提交成功！
INFO - 2021-08-31 19:34:57,841 - new_apply_order.py[line:181]: 联系人信息提交成功！
INFO - 2021-08-31 19:34:58,313 - new_apply_order.py[line:198]: 创建预审订单成功！
INFO - 2021-08-31 19:34:58,334 - new_apply_order.py[line:206]: 预审状态修改为通过,更新条数 1
INFO - 2021-08-31 19:34:58,352 - new_apply_order.py[line:209]: 更新初始额度！更新条数 1
INFO - 2021-08-31 19:34:58,652 - new_apply_order.py[line:221]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-08-31 19:34:58,687 - new_apply_order.py[line:230]: 视频认证通过！
INFO - 2021-08-31 19:34:59,666 - new_apply_order.py[line:276]: bvn和银行卡绑卡认证通过！
INFO - 2021-08-31 19:34:59,954 - new_apply_order.py[line:297]: user更新1条
INFO - 2021-08-31 19:35:00,169 - new_apply_order.py[line:317]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-08-31 19:35:01,208 - new_apply_order.py[line:323]: 订单表更新1条，信审更新1条
INFO - 2021-08-31 19:35:01,552 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 19:35:01,587 - new_apply_order.py[line:342]: 订单回调复审通过成功！
INFO - 2021-08-31 19:35:02,341 - new_apply_order.py[line:358]: 获取token成功！token=bearer bf51653c-283e-47c5-b902-66a96a35688d！
INFO - 2021-08-31 19:35:02,680 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 19:35:02,993 - new_apply_order.py[line:370]: 后台已触发放款成功！
INFO - 2021-08-31 19:35:03,002 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 19:35:03,011 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 19:35:04,354 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 19:35:04,368 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 19:35:04,372 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 19:35:04,678 - new_apply_order.py[line:540]: 校验重试查询第1次
ERROR - 2021-08-31 19:35:05,691 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-08-31 19:35:05,691 - new_apply_order.py[line:437]: {'app': 'quickcash', 'loan_order_id': '1432668228008415232', 'mobile': '01630409697', 'order_status': 35}
INFO - 2021-08-31 19:35:06,192 - new_apply_order.py[line:540]: 校验重试查询第2次
ERROR - 2021-08-31 19:35:07,210 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-08-31 19:35:07,211 - new_apply_order.py[line:437]: {'app': 'quickcash', 'loan_order_id': '1432668228008415232', 'mobile': '01630409697', 'order_status': 35}
INFO - 2021-08-31 19:35:07,715 - new_apply_order.py[line:540]: 校验重试查询第3次
ERROR - 2021-08-31 19:35:08,733 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-08-31 19:35:08,734 - new_apply_order.py[line:437]: {'app': 'quickcash', 'loan_order_id': '1432668228008415232', 'mobile': '01630409697', 'order_status': 35}
INFO - 2021-08-31 19:35:09,237 - new_apply_order.py[line:540]: 校验重试查询第4次
INFO - 2021-08-31 19:35:10,255 - new_apply_order.py[line:434]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-08-31 19:35:10,255 - new_apply_order.py[line:437]: {'app': 'quickcash', 'loan_order_id': '1432668228008415232', 'mobile': '01630409697', 'order_status': 40}
INFO - 2021-08-31 19:35:10,256 - new_apply_order.py[line:557]: ===========完成第【1】次进件===========
INFO - 2021-08-31 19:35:10,256 - new_apply_order.py[line:517]: 开始第 quickcash【2】次进件……
INFO - 2021-08-31 19:35:10,257 - new_apply_order.py[line:79]: ======【nga测试环境】生成手机号：01630409710 ======
INFO - 2021-08-31 19:35:10,607 - new_apply_order.py[line:86]: 01630409710 检测用户存在成功！
INFO - 2021-08-31 19:35:10,638 - new_apply_order.py[line:93]: 01630409710 短信发送成功！
INFO - 2021-08-31 19:35:10,672 - new_apply_order.py[line:103]: 01630409710 注册成功！
INFO - 2021-08-31 19:35:10,714 - new_apply_order.py[line:113]: 01630409710 登录短信发送成功！
INFO - 2021-08-31 19:35:10,756 - new_apply_order.py[line:121]: userId=6204057725073891328,mobile=01630409710,token=b1b801f77801570fcce3f4c721e1d061 登录成功
INFO - 2021-08-31 19:35:10,824 - new_apply_order.py[line:172]: 个人信息提交成功！
INFO - 2021-08-31 19:35:10,867 - new_apply_order.py[line:181]: 联系人信息提交成功！
INFO - 2021-08-31 19:35:11,289 - new_apply_order.py[line:198]: 创建预审订单成功！
INFO - 2021-08-31 19:35:11,307 - new_apply_order.py[line:206]: 预审状态修改为通过,更新条数 1
INFO - 2021-08-31 19:35:11,325 - new_apply_order.py[line:209]: 更新初始额度！更新条数 1
INFO - 2021-08-31 19:35:11,570 - new_apply_order.py[line:221]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-08-31 19:35:11,609 - new_apply_order.py[line:230]: 视频认证通过！
INFO - 2021-08-31 19:35:12,593 - new_apply_order.py[line:276]: bvn和银行卡绑卡认证通过！
INFO - 2021-08-31 19:35:12,893 - new_apply_order.py[line:297]: user更新1条
INFO - 2021-08-31 19:35:13,059 - new_apply_order.py[line:317]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-08-31 19:35:14,094 - new_apply_order.py[line:323]: 订单表更新1条，信审更新1条
INFO - 2021-08-31 19:35:14,437 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 19:35:14,472 - new_apply_order.py[line:342]: 订单回调复审通过成功！
INFO - 2021-08-31 19:35:15,226 - new_apply_order.py[line:358]: 获取token成功！token=bearer bf51653c-283e-47c5-b902-66a96a35688d！
INFO - 2021-08-31 19:35:15,587 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 19:35:15,899 - new_apply_order.py[line:370]: 后台已触发放款成功！
INFO - 2021-08-31 19:35:15,905 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 19:35:15,912 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 19:35:17,256 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 19:35:17,274 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 19:35:17,282 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 19:35:17,585 - new_apply_order.py[line:540]: 校验重试查询第1次
ERROR - 2021-08-31 19:35:18,604 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-08-31 19:35:18,604 - new_apply_order.py[line:437]: {'app': 'quickcash', 'loan_order_id': '1432668282576310272', 'mobile': '01630409710', 'order_status': 35}
INFO - 2021-08-31 19:35:19,109 - new_apply_order.py[line:540]: 校验重试查询第2次
INFO - 2021-08-31 19:35:20,124 - new_apply_order.py[line:434]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-08-31 19:35:20,124 - new_apply_order.py[line:437]: {'app': 'quickcash', 'loan_order_id': '1432668282576310272', 'mobile': '01630409710', 'order_status': 40}
INFO - 2021-08-31 19:35:20,125 - new_apply_order.py[line:557]: ===========完成第【2】次进件===========
INFO - 2021-08-31 19:35:20,125 - new_apply_order.py[line:560]: ======完成第【2】次进件,耗时22.96s=====
