INFO - 2021-09-22 09:37:46,559 - new_apply_order.py[line:696]: 开始第 Mipeso【1】次进件……
INFO - 2021-09-22 09:37:46,731 - new_apply_order.py[line:75]: 更新脏数据8条
INFO - 2021-09-22 09:37:46,732 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274666 ======
INFO - 2021-09-22 09:37:47,146 - new_apply_order.py[line:95]: 1632274666 检测用户存在成功！
INFO - 2021-09-22 09:37:47,203 - new_apply_order.py[line:104]: 1632274666 短信发送成功！
INFO - 2021-09-22 09:37:47,251 - new_apply_order.py[line:117]: 1632274666 注册成功！
INFO - 2021-09-22 09:37:47,313 - new_apply_order.py[line:133]: 1632274666 登录短信发送成功！
INFO - 2021-09-22 09:37:47,364 - new_apply_order.py[line:143]: userId=4953588728367030272,mobile=1632274666,token=bd5bcab34f1ead7339d8768f5e1040c7 登录成功
INFO - 2021-09-22 09:37:47,446 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:37:48,050 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:37:48,070 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:37:48,088 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:37:50,636 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:37:50,768 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:37:51,592 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:37:52,261 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:37:52,499 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:37:53,533 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:37:53,883 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:37:53,940 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:37:54,811 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:37:55,158 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:37:55,759 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:37:55,775 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:37:55,785 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:37:57,130 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:37:57,148 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:37:57,156 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:37:57,507 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:37:57,819 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:37:58,835 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:37:58,836 - new_apply_order.py[line:616]: {'app': 'Mipeso', 'loan_order_id': '1440490485837729792', 'mobile': '1632274666', 'order_status': 35}
INFO - 2021-09-22 09:37:59,724 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:37:59,837 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:37:59,838 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:38:00,854 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:38:00,854 - new_apply_order.py[line:616]: {'app': 'Mipeso', 'loan_order_id': '1440490485837729792', 'mobile': '1632274666', 'order_status': 40}
INFO - 2021-09-22 09:38:00,856 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:38:00,856 - new_apply_order.py[line:696]: 开始第 Mipeso【2】次进件……
INFO - 2021-09-22 09:38:00,918 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953588728367030272"
INFO - 2021-09-22 09:38:01,031 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:38:01,031 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274680 ======
INFO - 2021-09-22 09:38:01,379 - new_apply_order.py[line:95]: 1632274680 检测用户存在成功！
INFO - 2021-09-22 09:38:01,426 - new_apply_order.py[line:104]: 1632274680 短信发送成功！
INFO - 2021-09-22 09:38:01,470 - new_apply_order.py[line:117]: 1632274680 注册成功！
INFO - 2021-09-22 09:38:01,533 - new_apply_order.py[line:133]: 1632274680 登录短信发送成功！
INFO - 2021-09-22 09:38:01,580 - new_apply_order.py[line:143]: userId=4953588788010033152,mobile=1632274680,token=487223d1783dfb7b5af21c5cfc5993e7 登录成功
INFO - 2021-09-22 09:38:01,651 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:38:02,067 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:38:02,087 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:38:02,105 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:38:04,732 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:38:04,875 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:38:05,694 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:38:06,250 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:38:06,449 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:38:07,487 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:38:07,841 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:07,909 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:38:08,712 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:38:09,061 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:09,375 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:38:09,387 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:38:09,397 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:38:10,754 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:10,777 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:38:10,784 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:38:11,132 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:11,446 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:38:12,464 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:38:12,464 - new_apply_order.py[line:616]: {'app': 'Mipeso', 'loan_order_id': '1440490545392652288', 'mobile': '1632274680', 'order_status': 35}
INFO - 2021-09-22 09:38:13,316 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:13,421 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:38:13,421 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:38:14,438 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:38:14,438 - new_apply_order.py[line:616]: {'app': 'Mipeso', 'loan_order_id': '1440490545392652288', 'mobile': '1632274680', 'order_status': 40}
INFO - 2021-09-22 09:38:14,439 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:38:14,439 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时27.88s=====
INFO - 2021-09-22 09:38:14,442 - new_apply_order.py[line:696]: 开始第 m_efectivo【1】次进件……
INFO - 2021-09-22 09:38:14,589 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953588788010033152"
INFO - 2021-09-22 09:38:14,610 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:38:14,610 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274694 ======
INFO - 2021-09-22 09:38:14,958 - new_apply_order.py[line:95]: 1632274694 检测用户存在成功！
INFO - 2021-09-22 09:38:15,006 - new_apply_order.py[line:104]: 1632274694 短信发送成功！
INFO - 2021-09-22 09:38:15,050 - new_apply_order.py[line:117]: 1632274694 注册成功！
INFO - 2021-09-22 09:38:15,104 - new_apply_order.py[line:133]: 1632274694 登录短信发送成功！
INFO - 2021-09-22 09:38:15,172 - new_apply_order.py[line:143]: userId=4953588844968681472,mobile=1632274694,token=9618360b0fcdbc6e3392d5823726a70c 登录成功
INFO - 2021-09-22 09:38:15,256 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:38:15,463 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:38:15,481 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:38:15,495 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:38:17,837 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:38:17,960 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:38:18,708 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:38:19,274 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:38:19,472 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:38:20,496 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:38:20,847 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:20,884 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:38:21,695 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:38:22,045 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:22,399 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:38:22,411 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:38:22,421 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:38:23,765 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:23,778 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:38:23,782 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:38:24,122 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:24,433 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:38:25,447 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:38:25,447 - new_apply_order.py[line:616]: {'app': 'm_efectivo', 'loan_order_id': '1440490602460352512', 'mobile': '1632274694', 'order_status': 35}
INFO - 2021-09-22 09:38:26,299 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:26,390 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:38:26,390 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:38:27,408 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:38:27,409 - new_apply_order.py[line:616]: {'app': 'm_efectivo', 'loan_order_id': '1440490602460352512', 'mobile': '1632274694', 'order_status': 40}
INFO - 2021-09-22 09:38:27,409 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:38:27,409 - new_apply_order.py[line:696]: 开始第 m_efectivo【2】次进件……
INFO - 2021-09-22 09:38:27,535 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953588844968681472"
INFO - 2021-09-22 09:38:27,593 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:38:27,593 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274707 ======
INFO - 2021-09-22 09:38:27,947 - new_apply_order.py[line:95]: 1632274707 检测用户存在成功！
INFO - 2021-09-22 09:38:27,987 - new_apply_order.py[line:104]: 1632274707 短信发送成功！
INFO - 2021-09-22 09:38:28,026 - new_apply_order.py[line:117]: 1632274707 注册成功！
INFO - 2021-09-22 09:38:28,084 - new_apply_order.py[line:133]: 1632274707 登录短信发送成功！
INFO - 2021-09-22 09:38:28,131 - new_apply_order.py[line:143]: userId=4953588899419136000,mobile=1632274707,token=0172daac701b6f821e365a89f5b2a08c 登录成功
INFO - 2021-09-22 09:38:28,204 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:38:28,415 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:38:28,431 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:38:28,446 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:38:30,976 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:38:31,105 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:38:31,803 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:38:32,354 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:38:32,529 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:38:33,573 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:38:33,922 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:33,962 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:38:34,744 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:38:35,097 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:35,395 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:38:35,404 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:38:35,412 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:38:36,761 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:36,778 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:38:36,788 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:38:37,135 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:37,447 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:38:38,461 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:38:38,461 - new_apply_order.py[line:616]: {'app': 'm_efectivo', 'loan_order_id': '1440490656839503872', 'mobile': '1632274707', 'order_status': 35}
INFO - 2021-09-22 09:38:39,315 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:39,417 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:38:39,418 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:38:40,433 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:38:40,433 - new_apply_order.py[line:616]: {'app': 'm_efectivo', 'loan_order_id': '1440490656839503872', 'mobile': '1632274707', 'order_status': 40}
INFO - 2021-09-22 09:38:40,433 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:38:40,434 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时25.99s=====
INFO - 2021-09-22 09:38:40,438 - new_apply_order.py[line:696]: 开始第 porpeso【1】次进件……
INFO - 2021-09-22 09:38:40,503 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953588899419136000"
INFO - 2021-09-22 09:38:40,617 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:38:40,618 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274720 ======
INFO - 2021-09-22 09:38:40,959 - new_apply_order.py[line:95]: 1632274720 检测用户存在成功！
INFO - 2021-09-22 09:38:41,010 - new_apply_order.py[line:104]: 1632274720 短信发送成功！
INFO - 2021-09-22 09:38:41,050 - new_apply_order.py[line:117]: 1632274720 注册成功！
INFO - 2021-09-22 09:38:41,102 - new_apply_order.py[line:133]: 1632274720 登录短信发送成功！
INFO - 2021-09-22 09:38:41,148 - new_apply_order.py[line:143]: userId=4953588954033168384,mobile=1632274720,token=8a4c8b894c2e742dd516562e5680d3ac 登录成功
INFO - 2021-09-22 09:38:41,220 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:38:41,606 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:38:41,623 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:38:41,640 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:38:44,107 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:38:44,225 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:38:44,964 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:38:45,514 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:38:45,695 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:38:46,736 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:38:47,094 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:47,134 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:38:47,897 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:38:48,255 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:48,540 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:38:48,573 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:38:48,581 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:38:49,923 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:49,934 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:38:49,939 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:38:50,279 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:50,588 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:38:51,605 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:38:51,605 - new_apply_order.py[line:616]: {'app': 'porpeso', 'loan_order_id': '1440490711378038784', 'mobile': '1632274720', 'order_status': 35}
INFO - 2021-09-22 09:38:52,455 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:38:52,548 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:38:52,548 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:38:53,586 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:38:53,587 - new_apply_order.py[line:616]: {'app': 'porpeso', 'loan_order_id': '1440490711378038784', 'mobile': '1632274720', 'order_status': 40}
INFO - 2021-09-22 09:38:53,588 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:38:53,588 - new_apply_order.py[line:696]: 开始第 porpeso【2】次进件……
INFO - 2021-09-22 09:38:53,695 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953588954033168384"
INFO - 2021-09-22 09:38:53,794 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:38:53,795 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274733 ======
INFO - 2021-09-22 09:38:54,144 - new_apply_order.py[line:95]: 1632274733 检测用户存在成功！
INFO - 2021-09-22 09:38:54,188 - new_apply_order.py[line:104]: 1632274733 短信发送成功！
INFO - 2021-09-22 09:38:54,226 - new_apply_order.py[line:117]: 1632274733 注册成功！
INFO - 2021-09-22 09:38:54,273 - new_apply_order.py[line:133]: 1632274733 登录短信发送成功！
INFO - 2021-09-22 09:38:54,316 - new_apply_order.py[line:143]: userId=4953589009293123584,mobile=1632274733,token=de31650102dff5b3830aa1cd72a49f6e 登录成功
INFO - 2021-09-22 09:38:54,382 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:38:54,570 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:38:54,586 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:38:54,599 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:38:57,104 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:38:57,224 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:38:57,967 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:38:58,527 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:38:58,694 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:38:59,734 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:39:00,086 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:00,126 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:39:00,889 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:39:01,229 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:01,525 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:39:01,537 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:39:01,547 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:39:02,932 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:02,943 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:39:02,950 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:39:03,305 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:03,619 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:39:04,637 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:39:04,637 - new_apply_order.py[line:616]: {'app': 'porpeso', 'loan_order_id': '1440490766562496512', 'mobile': '1632274733', 'order_status': 35}
INFO - 2021-09-22 09:39:05,576 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:05,717 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:39:05,717 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:39:06,732 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:39:06,732 - new_apply_order.py[line:616]: {'app': 'porpeso', 'loan_order_id': '1440490766562496512', 'mobile': '1632274733', 'order_status': 40}
INFO - 2021-09-22 09:39:06,733 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:39:06,733 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时26.30s=====
INFO - 2021-09-22 09:39:06,736 - new_apply_order.py[line:696]: 开始第 Prestamo【1】次进件……
INFO - 2021-09-22 09:39:06,849 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953589009293123584"
INFO - 2021-09-22 09:39:06,904 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:39:06,905 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274746 ======
INFO - 2021-09-22 09:39:07,251 - new_apply_order.py[line:95]: 1632274746 检测用户存在成功！
INFO - 2021-09-22 09:39:07,304 - new_apply_order.py[line:104]: 1632274746 短信发送成功！
INFO - 2021-09-22 09:39:07,348 - new_apply_order.py[line:117]: 1632274746 注册成功！
INFO - 2021-09-22 09:39:07,402 - new_apply_order.py[line:133]: 1632274746 登录短信发送成功！
INFO - 2021-09-22 09:39:07,449 - new_apply_order.py[line:143]: userId=4953589064322392064,mobile=1632274746,token=09db5f4241ce3a9b8b2e2ef2a2b402f8 登录成功
INFO - 2021-09-22 09:39:07,527 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:39:07,959 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:39:07,974 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:39:07,986 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:39:10,484 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:39:10,604 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:39:11,254 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:39:11,834 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:39:12,029 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:39:13,058 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:39:13,411 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:13,451 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:39:14,238 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:39:14,584 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:14,892 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:39:14,905 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:39:14,914 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:39:16,288 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:16,303 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:39:16,310 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:39:16,656 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:16,969 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:39:18,003 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:39:18,003 - new_apply_order.py[line:616]: {'app': 'Prestamo', 'loan_order_id': '1440490821725982720', 'mobile': '1632274746', 'order_status': 35}
INFO - 2021-09-22 09:39:18,863 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:18,975 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:39:18,975 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:39:19,991 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:39:19,992 - new_apply_order.py[line:616]: {'app': 'Prestamo', 'loan_order_id': '1440490821725982720', 'mobile': '1632274746', 'order_status': 40}
INFO - 2021-09-22 09:39:19,993 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:39:19,993 - new_apply_order.py[line:696]: 开始第 Prestamo【2】次进件……
INFO - 2021-09-22 09:39:20,122 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953589064322392064"
INFO - 2021-09-22 09:39:20,161 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:39:20,162 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274759 ======
INFO - 2021-09-22 09:39:20,512 - new_apply_order.py[line:95]: 1632274759 检测用户存在成功！
INFO - 2021-09-22 09:39:20,554 - new_apply_order.py[line:104]: 1632274759 短信发送成功！
INFO - 2021-09-22 09:39:20,595 - new_apply_order.py[line:117]: 1632274759 注册成功！
INFO - 2021-09-22 09:39:20,646 - new_apply_order.py[line:133]: 1632274759 登录短信发送成功！
INFO - 2021-09-22 09:39:20,692 - new_apply_order.py[line:143]: userId=4953589119888531456,mobile=1632274759,token=6c6914744425bad4e580c9875686d6cd 登录成功
INFO - 2021-09-22 09:39:20,764 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:39:20,961 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:39:20,977 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:39:20,996 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:39:23,364 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:39:23,467 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:39:24,219 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:39:24,788 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:39:24,963 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:39:25,999 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:39:26,357 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:26,395 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:39:27,214 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:39:27,563 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:27,872 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:39:27,883 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:39:27,893 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:39:29,251 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:29,265 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:39:29,272 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:39:29,621 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:29,935 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:39:30,949 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:39:30,949 - new_apply_order.py[line:616]: {'app': 'Prestamo', 'loan_order_id': '1440490877225013248', 'mobile': '1632274759', 'order_status': 35}
INFO - 2021-09-22 09:39:31,796 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:31,899 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:39:31,900 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:39:32,914 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:39:32,915 - new_apply_order.py[line:616]: {'app': 'Prestamo', 'loan_order_id': '1440490877225013248', 'mobile': '1632274759', 'order_status': 40}
INFO - 2021-09-22 09:39:32,915 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:39:32,915 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时26.18s=====
INFO - 2021-09-22 09:39:32,919 - new_apply_order.py[line:696]: 开始第 askborrow【1】次进件……
INFO - 2021-09-22 09:39:32,991 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953589119888531456"
INFO - 2021-09-22 09:39:33,094 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:39:33,095 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274772 ======
INFO - 2021-09-22 09:39:33,443 - new_apply_order.py[line:95]: 1632274772 检测用户存在成功！
INFO - 2021-09-22 09:39:33,489 - new_apply_order.py[line:104]: 1632274772 短信发送成功！
INFO - 2021-09-22 09:39:33,530 - new_apply_order.py[line:117]: 1632274772 注册成功！
INFO - 2021-09-22 09:39:33,579 - new_apply_order.py[line:133]: 1632274772 登录短信发送成功！
INFO - 2021-09-22 09:39:33,633 - new_apply_order.py[line:143]: userId=4953589174137659392,mobile=1632274772,token=06ebe9d919ce0e4b26293907687f7b96 登录成功
INFO - 2021-09-22 09:39:33,706 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:39:34,106 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:39:34,124 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:39:34,144 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:39:36,482 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:39:36,604 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:39:37,348 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:39:38,003 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:39:38,196 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:39:39,228 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:39:39,577 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:39,612 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:39:40,377 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:39:40,719 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:41,015 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:39:41,028 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:39:41,038 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:39:42,390 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:42,407 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:39:42,414 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:39:42,768 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:43,083 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:39:44,101 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:39:44,101 - new_apply_order.py[line:616]: {'app': 'askborrow', 'loan_order_id': '1440490931520278528', 'mobile': '1632274772', 'order_status': 35}
INFO - 2021-09-22 09:39:44,956 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:44,968 - new_apply_order.py[line:719]: 校验重试查询第2次
ERROR - 2021-09-22 09:39:45,986 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:39:45,986 - new_apply_order.py[line:616]: {'app': 'askborrow', 'loan_order_id': '1440490931520278528', 'mobile': '1632274772', 'order_status': 35}
INFO - 2021-09-22 09:39:46,833 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:46,844 - new_apply_order.py[line:719]: 校验重试查询第3次
ERROR - 2021-09-22 09:39:47,861 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:39:47,862 - new_apply_order.py[line:616]: {'app': 'askborrow', 'loan_order_id': '1440490931520278528', 'mobile': '1632274772', 'order_status': 35}
INFO - 2021-09-22 09:39:48,717 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:48,729 - new_apply_order.py[line:719]: 校验重试查询第4次
ERROR - 2021-09-22 09:39:49,743 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:39:49,743 - new_apply_order.py[line:616]: {'app': 'askborrow', 'loan_order_id': '1440490931520278528', 'mobile': '1632274772', 'order_status': 35}
INFO - 2021-09-22 09:39:50,594 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:50,605 - new_apply_order.py[line:719]: 校验重试查询第5次
ERROR - 2021-09-22 09:39:51,618 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:39:51,618 - new_apply_order.py[line:616]: {'app': 'askborrow', 'loan_order_id': '1440490931520278528', 'mobile': '1632274772', 'order_status': 35}
INFO - 2021-09-22 09:39:52,473 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:39:52,578 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:39:52,578 - new_apply_order.py[line:719]: 校验重试查询第6次
INFO - 2021-09-22 09:39:53,596 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:39:53,596 - new_apply_order.py[line:616]: {'app': 'askborrow', 'loan_order_id': '1440490931520278528', 'mobile': '1632274772', 'order_status': 40}
INFO - 2021-09-22 09:39:53,597 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:39:53,597 - new_apply_order.py[line:696]: 开始第 askborrow【2】次进件……
INFO - 2021-09-22 09:39:53,698 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953589174137659392"
INFO - 2021-09-22 09:39:53,767 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:39:53,768 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274793 ======
INFO - 2021-09-22 09:39:54,116 - new_apply_order.py[line:95]: 1632274793 检测用户存在成功！
INFO - 2021-09-22 09:39:54,161 - new_apply_order.py[line:104]: 1632274793 短信发送成功！
INFO - 2021-09-22 09:39:54,203 - new_apply_order.py[line:117]: 1632274793 注册成功！
INFO - 2021-09-22 09:39:54,255 - new_apply_order.py[line:133]: 1632274793 登录短信发送成功！
INFO - 2021-09-22 09:39:54,304 - new_apply_order.py[line:143]: userId=4953589260838117376,mobile=1632274793,token=0b5cbf07a30cc697eaf3489fe676cc89 登录成功
INFO - 2021-09-22 09:39:54,382 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:39:54,571 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:39:54,589 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:39:54,606 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:39:56,972 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:39:57,084 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:39:57,840 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:39:58,418 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:39:58,593 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:39:59,624 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:39:59,976 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:00,025 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:40:00,840 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:40:01,188 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:01,508 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:40:01,519 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:40:01,528 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:40:02,881 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:02,894 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:40:02,900 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:40:03,254 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:03,566 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:40:04,580 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:40:04,580 - new_apply_order.py[line:616]: {'app': 'askborrow', 'loan_order_id': '1440491018224930816', 'mobile': '1632274793', 'order_status': 35}
INFO - 2021-09-22 09:40:05,443 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:05,540 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:40:05,541 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:40:06,557 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:40:06,557 - new_apply_order.py[line:616]: {'app': 'askborrow', 'loan_order_id': '1440491018224930816', 'mobile': '1632274793', 'order_status': 40}
INFO - 2021-09-22 09:40:06,558 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:40:06,558 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时33.64s=====
INFO - 2021-09-22 09:40:06,562 - new_apply_order.py[line:696]: 开始第 G_Prestamo【1】次进件……
INFO - 2021-09-22 09:40:06,642 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953589260838117376"
INFO - 2021-09-22 09:40:06,737 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:40:06,737 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274806 ======
INFO - 2021-09-22 09:40:07,085 - new_apply_order.py[line:95]: 1632274806 检测用户存在成功！
INFO - 2021-09-22 09:40:07,131 - new_apply_order.py[line:104]: 1632274806 短信发送成功！
INFO - 2021-09-22 09:40:07,170 - new_apply_order.py[line:117]: 1632274806 注册成功！
INFO - 2021-09-22 09:40:07,220 - new_apply_order.py[line:133]: 1632274806 登录短信发送成功！
INFO - 2021-09-22 09:40:07,265 - new_apply_order.py[line:143]: userId=4953589315238240256,mobile=1632274806,token=ce31c268ddc6ecb605ae3a030bb4d784 登录成功
INFO - 2021-09-22 09:40:07,338 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:40:07,733 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:40:07,750 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:40:07,766 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:40:10,222 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:40:10,323 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:40:11,221 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:40:11,832 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:40:12,012 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:40:13,044 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:40:13,390 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:13,427 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:40:14,223 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:40:14,571 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:14,879 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:40:14,892 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:40:14,901 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:40:16,251 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:16,267 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:40:16,273 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:40:16,622 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:16,939 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:40:17,953 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:40:17,953 - new_apply_order.py[line:616]: {'app': 'G_Prestamo', 'loan_order_id': '1440491072587304960', 'mobile': '1632274806', 'order_status': 35}
INFO - 2021-09-22 09:40:18,807 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:18,921 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:40:18,921 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:40:19,938 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:40:19,938 - new_apply_order.py[line:616]: {'app': 'G_Prestamo', 'loan_order_id': '1440491072587304960', 'mobile': '1632274806', 'order_status': 40}
INFO - 2021-09-22 09:40:19,939 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:40:19,939 - new_apply_order.py[line:696]: 开始第 G_Prestamo【2】次进件……
INFO - 2021-09-22 09:40:20,089 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953589315238240256"
INFO - 2021-09-22 09:40:20,119 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:40:20,120 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274819 ======
INFO - 2021-09-22 09:40:20,463 - new_apply_order.py[line:95]: 1632274819 检测用户存在成功！
INFO - 2021-09-22 09:40:20,509 - new_apply_order.py[line:104]: 1632274819 短信发送成功！
INFO - 2021-09-22 09:40:20,550 - new_apply_order.py[line:117]: 1632274819 注册成功！
INFO - 2021-09-22 09:40:20,602 - new_apply_order.py[line:133]: 1632274819 登录短信发送成功！
INFO - 2021-09-22 09:40:20,648 - new_apply_order.py[line:143]: userId=4953589371341250560,mobile=1632274819,token=3d98624c8bca7f513971f6f0ac9c78ad 登录成功
INFO - 2021-09-22 09:40:20,723 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:40:20,920 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:40:20,939 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:40:20,954 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:40:23,484 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:40:23,624 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:40:24,348 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:40:24,881 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:40:25,037 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:40:26,064 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:40:26,417 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:26,456 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:40:27,184 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:40:27,525 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:27,863 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:40:27,871 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:40:27,878 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:40:29,219 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:29,229 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:40:29,234 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:40:29,576 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:29,887 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:40:30,903 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:40:30,904 - new_apply_order.py[line:616]: {'app': 'G_Prestamo', 'loan_order_id': '1440491128707092480', 'mobile': '1632274819', 'order_status': 35}
INFO - 2021-09-22 09:40:31,754 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:31,764 - new_apply_order.py[line:719]: 校验重试查询第2次
ERROR - 2021-09-22 09:40:32,774 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:40:32,775 - new_apply_order.py[line:616]: {'app': 'G_Prestamo', 'loan_order_id': '1440491128707092480', 'mobile': '1632274819', 'order_status': 35}
INFO - 2021-09-22 09:40:33,662 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:33,771 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:40:33,772 - new_apply_order.py[line:719]: 校验重试查询第3次
INFO - 2021-09-22 09:40:34,781 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:40:34,781 - new_apply_order.py[line:616]: {'app': 'G_Prestamo', 'loan_order_id': '1440491128707092480', 'mobile': '1632274819', 'order_status': 40}
INFO - 2021-09-22 09:40:34,781 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:40:34,782 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时28.22s=====
INFO - 2021-09-22 09:40:34,784 - new_apply_order.py[line:696]: 开始第 miprestamo【1】次进件……
INFO - 2021-09-22 09:40:34,854 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953589371341250560"
INFO - 2021-09-22 09:40:34,951 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:40:34,952 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274834 ======
INFO - 2021-09-22 09:40:35,313 - new_apply_order.py[line:95]: 1632274834 检测用户存在成功！
INFO - 2021-09-22 09:40:35,358 - new_apply_order.py[line:104]: 1632274834 短信发送成功！
INFO - 2021-09-22 09:40:35,400 - new_apply_order.py[line:117]: 1632274834 注册成功！
INFO - 2021-09-22 09:40:35,449 - new_apply_order.py[line:133]: 1632274834 登录短信发送成功！
INFO - 2021-09-22 09:40:35,496 - new_apply_order.py[line:143]: userId=4953589433626664960,mobile=1632274834,token=6ca1e0bd3ca26a781a6d1e6fd02ba684 登录成功
INFO - 2021-09-22 09:40:35,565 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:40:35,965 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:40:35,986 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:40:36,002 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:40:38,511 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:40:38,628 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:40:39,352 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:40:39,880 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:40:40,041 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:40:41,076 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:40:41,423 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:41,458 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:40:42,238 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:40:42,585 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:42,904 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:40:42,918 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:40:42,928 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:40:44,273 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:44,293 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:40:44,300 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:40:44,650 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:44,961 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:40:45,974 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:40:45,975 - new_apply_order.py[line:616]: {'app': 'miprestamo', 'loan_order_id': '1440491190937980928', 'mobile': '1632274834', 'order_status': 35}
INFO - 2021-09-22 09:40:46,829 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:46,919 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:40:46,919 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:40:47,934 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:40:47,934 - new_apply_order.py[line:616]: {'app': 'miprestamo', 'loan_order_id': '1440491190937980928', 'mobile': '1632274834', 'order_status': 40}
INFO - 2021-09-22 09:40:47,935 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:40:47,935 - new_apply_order.py[line:696]: 开始第 miprestamo【2】次进件……
INFO - 2021-09-22 09:40:48,034 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953589433626664960"
INFO - 2021-09-22 09:40:48,115 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:40:48,116 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274847 ======
INFO - 2021-09-22 09:40:48,467 - new_apply_order.py[line:95]: 1632274847 检测用户存在成功！
INFO - 2021-09-22 09:40:48,526 - new_apply_order.py[line:104]: 1632274847 短信发送成功！
INFO - 2021-09-22 09:40:48,574 - new_apply_order.py[line:117]: 1632274847 注册成功！
INFO - 2021-09-22 09:40:48,628 - new_apply_order.py[line:133]: 1632274847 登录短信发送成功！
INFO - 2021-09-22 09:40:48,677 - new_apply_order.py[line:143]: userId=4953589488915980288,mobile=1632274847,token=d926bf2f0f7271c6363afff2392eb120 登录成功
INFO - 2021-09-22 09:40:48,750 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:40:48,959 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:40:48,980 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:40:48,999 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:40:51,476 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:40:51,608 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:40:52,341 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:40:52,977 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:40:53,168 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:40:54,205 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:40:54,565 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:54,604 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:40:55,369 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:40:55,715 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:56,035 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:40:56,046 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:40:56,055 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:40:57,404 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:57,421 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:40:57,430 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:40:57,781 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:40:58,093 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:40:59,106 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:40:59,106 - new_apply_order.py[line:616]: {'app': 'miprestamo', 'loan_order_id': '1440491246265044992', 'mobile': '1632274847', 'order_status': 35}
INFO - 2021-09-22 09:40:59,963 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:00,058 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:41:00,058 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:41:01,071 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:41:01,071 - new_apply_order.py[line:616]: {'app': 'miprestamo', 'loan_order_id': '1440491246265044992', 'mobile': '1632274847', 'order_status': 40}
INFO - 2021-09-22 09:41:01,072 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:41:01,072 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时26.29s=====
INFO - 2021-09-22 09:41:01,075 - new_apply_order.py[line:696]: 开始第 borrowedpop【1】次进件……
INFO - 2021-09-22 09:41:01,201 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953589488915980288"
INFO - 2021-09-22 09:41:01,236 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:41:01,237 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274861 ======
INFO - 2021-09-22 09:41:01,581 - new_apply_order.py[line:95]: 1632274861 检测用户存在成功！
INFO - 2021-09-22 09:41:01,617 - new_apply_order.py[line:104]: 1632274861 短信发送成功！
INFO - 2021-09-22 09:41:01,653 - new_apply_order.py[line:117]: 1632274861 注册成功！
INFO - 2021-09-22 09:41:01,699 - new_apply_order.py[line:133]: 1632274861 登录短信发送成功！
INFO - 2021-09-22 09:41:01,742 - new_apply_order.py[line:143]: userId=4953589543785865216,mobile=1632274861,token=5360e8015caeab7186f8ff5cfd2accb7 登录成功
INFO - 2021-09-22 09:41:01,807 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:41:02,200 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:41:02,220 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:41:02,235 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:41:04,733 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:41:04,861 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:41:05,619 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:41:06,323 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:41:06,511 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:41:07,541 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:41:07,899 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:07,939 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:41:08,735 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:41:09,084 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:09,381 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:41:09,394 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:41:09,403 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:41:10,753 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:10,766 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:41:10,774 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:41:11,127 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:11,439 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:41:12,447 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:41:12,447 - new_apply_order.py[line:616]: {'app': 'borrowedpop', 'loan_order_id': '1440491301051043840', 'mobile': '1632274861', 'order_status': 35}
INFO - 2021-09-22 09:41:13,291 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:13,296 - new_apply_order.py[line:719]: 校验重试查询第2次
ERROR - 2021-09-22 09:41:14,312 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:41:14,312 - new_apply_order.py[line:616]: {'app': 'borrowedpop', 'loan_order_id': '1440491301051043840', 'mobile': '1632274861', 'order_status': 35}
INFO - 2021-09-22 09:41:15,167 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:15,277 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:41:15,278 - new_apply_order.py[line:719]: 校验重试查询第3次
INFO - 2021-09-22 09:41:16,290 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:41:16,290 - new_apply_order.py[line:616]: {'app': 'borrowedpop', 'loan_order_id': '1440491301051043840', 'mobile': '1632274861', 'order_status': 40}
INFO - 2021-09-22 09:41:16,291 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:41:16,291 - new_apply_order.py[line:696]: 开始第 borrowedpop【2】次进件……
INFO - 2021-09-22 09:41:16,445 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953589543785865216"
INFO - 2021-09-22 09:41:16,471 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:41:16,471 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274876 ======
INFO - 2021-09-22 09:41:16,817 - new_apply_order.py[line:95]: 1632274876 检测用户存在成功！
INFO - 2021-09-22 09:41:16,853 - new_apply_order.py[line:104]: 1632274876 短信发送成功！
INFO - 2021-09-22 09:41:16,890 - new_apply_order.py[line:117]: 1632274876 注册成功！
INFO - 2021-09-22 09:41:16,935 - new_apply_order.py[line:133]: 1632274876 登录短信发送成功！
INFO - 2021-09-22 09:41:16,975 - new_apply_order.py[line:143]: userId=4953589607702863872,mobile=1632274876,token=772096d43d45250b6150052f27c0c1cb 登录成功
INFO - 2021-09-22 09:41:17,040 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:41:17,235 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:41:17,256 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:41:17,270 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:41:19,608 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:41:19,723 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:41:20,482 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:41:21,042 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:41:21,214 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:41:22,240 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:41:22,588 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:22,629 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:41:23,389 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:41:23,735 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:24,012 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:41:24,024 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:41:24,033 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:41:25,383 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:25,395 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:41:25,402 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:41:25,758 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:26,072 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:41:27,085 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:41:27,085 - new_apply_order.py[line:616]: {'app': 'borrowedpop', 'loan_order_id': '1440491364909322240', 'mobile': '1632274876', 'order_status': 35}
INFO - 2021-09-22 09:41:27,940 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:28,058 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:41:28,058 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:41:29,075 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:41:29,075 - new_apply_order.py[line:616]: {'app': 'borrowedpop', 'loan_order_id': '1440491364909322240', 'mobile': '1632274876', 'order_status': 40}
INFO - 2021-09-22 09:41:29,076 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:41:29,076 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时28.00s=====
INFO - 2021-09-22 09:41:29,080 - new_apply_order.py[line:696]: 开始第 goodloan【1】次进件……
INFO - 2021-09-22 09:41:29,214 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953589607702863872"
INFO - 2021-09-22 09:41:29,255 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:41:29,255 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274889 ======
INFO - 2021-09-22 09:41:29,604 - new_apply_order.py[line:95]: 1632274889 检测用户存在成功！
INFO - 2021-09-22 09:41:29,650 - new_apply_order.py[line:104]: 1632274889 短信发送成功！
INFO - 2021-09-22 09:41:29,691 - new_apply_order.py[line:117]: 1632274889 注册成功！
INFO - 2021-09-22 09:41:29,744 - new_apply_order.py[line:133]: 1632274889 登录短信发送成功！
INFO - 2021-09-22 09:41:29,810 - new_apply_order.py[line:143]: userId=4953589661385760768,mobile=1632274889,token=eec42dcfeffa28b7adef344e53baff2c 登录成功
INFO - 2021-09-22 09:41:29,896 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:41:30,313 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:41:30,334 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:41:30,352 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:41:33,734 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:41:33,885 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:41:34,695 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:41:35,278 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:41:35,446 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:41:36,476 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:41:36,820 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:36,862 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:41:37,636 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:41:38,025 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:38,358 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:41:38,370 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:41:38,379 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:41:39,728 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:39,744 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:41:39,751 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:41:40,101 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:40,415 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:41:41,431 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:41:41,432 - new_apply_order.py[line:616]: {'app': 'goodloan', 'loan_order_id': '1440491418873237504', 'mobile': '1632274889', 'order_status': 35}
INFO - 2021-09-22 09:41:42,287 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:42,382 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:41:42,382 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:41:43,399 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:41:43,399 - new_apply_order.py[line:616]: {'app': 'goodloan', 'loan_order_id': '1440491418873237504', 'mobile': '1632274889', 'order_status': 40}
INFO - 2021-09-22 09:41:43,400 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:41:43,400 - new_apply_order.py[line:696]: 开始第 goodloan【2】次进件……
INFO - 2021-09-22 09:41:43,455 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953589661385760768"
INFO - 2021-09-22 09:41:43,568 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:41:43,569 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274903 ======
INFO - 2021-09-22 09:41:43,918 - new_apply_order.py[line:95]: 1632274903 检测用户存在成功！
INFO - 2021-09-22 09:41:43,959 - new_apply_order.py[line:104]: 1632274903 短信发送成功！
INFO - 2021-09-22 09:41:43,998 - new_apply_order.py[line:117]: 1632274903 注册成功！
INFO - 2021-09-22 09:41:44,049 - new_apply_order.py[line:133]: 1632274903 登录短信发送成功！
INFO - 2021-09-22 09:41:44,097 - new_apply_order.py[line:143]: userId=4953589721402056704,mobile=1632274903,token=d5074179bdd7b0641a3918844fa79473 登录成功
INFO - 2021-09-22 09:41:44,171 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:41:44,404 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:41:44,420 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:41:44,433 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:41:46,604 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:41:46,708 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:41:47,460 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:41:48,010 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:41:48,178 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:41:49,217 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:41:49,579 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:49,615 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:41:50,389 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:41:50,733 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:51,030 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:41:51,042 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:41:51,052 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:41:52,396 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:52,413 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:41:52,421 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:41:52,791 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:53,103 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:41:54,120 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:41:54,120 - new_apply_order.py[line:616]: {'app': 'goodloan', 'loan_order_id': '1440491478751121408', 'mobile': '1632274903', 'order_status': 35}
INFO - 2021-09-22 09:41:54,971 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:41:55,078 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:41:55,078 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:41:56,091 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:41:56,091 - new_apply_order.py[line:616]: {'app': 'goodloan', 'loan_order_id': '1440491478751121408', 'mobile': '1632274903', 'order_status': 40}
INFO - 2021-09-22 09:41:56,092 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:41:56,092 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时27.01s=====
INFO - 2021-09-22 09:41:56,096 - new_apply_order.py[line:696]: 开始第 Hola_efectivo【1】次进件……
INFO - 2021-09-22 09:41:56,166 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953589721402056704"
INFO - 2021-09-22 09:41:56,272 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:41:56,273 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274916 ======
INFO - 2021-09-22 09:41:56,622 - new_apply_order.py[line:95]: 1632274916 检测用户存在成功！
INFO - 2021-09-22 09:41:56,665 - new_apply_order.py[line:104]: 1632274916 短信发送成功！
INFO - 2021-09-22 09:41:56,705 - new_apply_order.py[line:117]: 1632274916 注册成功！
INFO - 2021-09-22 09:41:56,755 - new_apply_order.py[line:133]: 1632274916 登录短信发送成功！
INFO - 2021-09-22 09:41:56,799 - new_apply_order.py[line:143]: userId=4953589774690689024,mobile=1632274916,token=890a7b763422267775dc872b32cde302 登录成功
INFO - 2021-09-22 09:41:56,878 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:41:57,070 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:41:57,088 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:41:57,102 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:41:59,486 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:41:59,619 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:42:00,469 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:42:01,017 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:42:01,173 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:42:02,215 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:42:02,566 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:02,606 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:42:03,378 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:42:03,728 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:04,022 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:42:04,034 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:42:04,043 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:42:05,408 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:05,424 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:42:05,430 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:42:05,764 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:06,073 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:42:07,087 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:42:07,087 - new_apply_order.py[line:616]: {'app': 'Hola_efectivo', 'loan_order_id': '1440491532043948032', 'mobile': '1632274916', 'order_status': 35}
INFO - 2021-09-22 09:42:07,935 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:08,033 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:42:08,034 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:42:09,048 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:42:09,049 - new_apply_order.py[line:616]: {'app': 'Hola_efectivo', 'loan_order_id': '1440491532043948032', 'mobile': '1632274916', 'order_status': 40}
INFO - 2021-09-22 09:42:09,049 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:42:09,050 - new_apply_order.py[line:696]: 开始第 Hola_efectivo【2】次进件……
INFO - 2021-09-22 09:42:09,199 - new_apply_order.py[line:60]: 删除redis key: "mx:cfs:user:userid:4953589774690689024"
INFO - 2021-09-22 09:42:09,220 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-09-22 09:42:09,220 - new_apply_order.py[line:82]: ======【mx测试环境】生成手机号：1632274929 ======
INFO - 2021-09-22 09:42:09,564 - new_apply_order.py[line:95]: 1632274929 检测用户存在成功！
INFO - 2021-09-22 09:42:09,608 - new_apply_order.py[line:104]: 1632274929 短信发送成功！
INFO - 2021-09-22 09:42:09,650 - new_apply_order.py[line:117]: 1632274929 注册成功！
INFO - 2021-09-22 09:42:09,702 - new_apply_order.py[line:133]: 1632274929 登录短信发送成功！
INFO - 2021-09-22 09:42:09,746 - new_apply_order.py[line:143]: userId=4953589828977565696,mobile=1632274929,token=cddebb472250eed38081e805e0dd662c 登录成功
INFO - 2021-09-22 09:42:09,812 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:42:10,215 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:42:10,230 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:42:10,240 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:42:12,673 - new_apply_order.py[line:285]: curp上传成功!
INFO - 2021-09-22 09:42:12,794 - new_apply_order.py[line:294]: curp_rfc校验通过！
INFO - 2021-09-22 09:42:13,586 - new_apply_order.py[line:305]: 人脸识别成功!
INFO - 2021-09-22 09:42:14,079 - new_apply_order.py[line:395]: 绑卡成功！
INFO - 2021-09-22 09:42:14,244 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:42:15,272 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:42:15,622 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:15,661 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:42:16,469 - new_apply_order.py[line:483]: 获取token成功！token=bearer 6d99a645-6c97-451c-bf85-0e109d3cce97！
INFO - 2021-09-22 09:42:16,820 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:17,128 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:42:17,139 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:42:17,149 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:42:18,505 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:18,520 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:42:18,526 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:42:18,875 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:19,186 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:42:20,202 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:42:20,203 - new_apply_order.py[line:616]: {'app': 'Hola_efectivo', 'loan_order_id': '1440491586284687360', 'mobile': '1632274929', 'order_status': 35}
INFO - 2021-09-22 09:42:21,049 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:21,155 - new_apply_order.py[line:568]: 放款回调成功！
INFO - 2021-09-22 09:42:21,156 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:42:22,172 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:42:22,172 - new_apply_order.py[line:616]: {'app': 'Hola_efectivo', 'loan_order_id': '1440491586284687360', 'mobile': '1632274929', 'order_status': 40}
INFO - 2021-09-22 09:42:22,173 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:42:22,173 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时26.08s=====
INFO - 2021-09-22 09:42:22,176 - new_apply_order.py[line:696]: 开始第 kencash【1】次进件……
INFO - 2021-09-22 09:42:22,177 - new_apply_order.py[line:82]: ======【ke测试环境】生成手机号：732274942 ======
INFO - 2021-09-22 09:42:22,600 - new_apply_order.py[line:95]: 732274942 检测用户存在成功！
INFO - 2021-09-22 09:42:22,758 - new_apply_order.py[line:104]: 732274942 短信发送成功！
INFO - 2021-09-22 09:42:22,845 - new_apply_order.py[line:117]: 732274942 注册成功！
INFO - 2021-09-22 09:42:22,914 - new_apply_order.py[line:133]: 732274942 登录短信发送成功！
INFO - 2021-09-22 09:42:22,994 - new_apply_order.py[line:143]: userId=6211881084247613440,mobile=732274942,token=c239640dae39f5afae4e0becc3aa29bf 登录成功
INFO - 2021-09-22 09:42:23,890 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:42:23,963 - new_apply_order.py[line:225]: 联系人信息提交成功！
INFO - 2021-09-22 09:42:25,285 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:42:25,304 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:42:25,322 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:42:25,594 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:42:25,647 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:42:26,003 - new_apply_order.py[line:404]: 绑卡成功！
INFO - 2021-09-22 09:42:26,465 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:42:27,501 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:42:27,910 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:27,990 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:42:28,822 - new_apply_order.py[line:483]: 获取token成功！token=bearer f0a0de17-f7e9-46f2-b8d0-60efbc3b30b9！
INFO - 2021-09-22 09:42:29,204 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:29,905 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:42:29,918 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:42:29,929 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:42:31,279 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:31,298 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:42:31,307 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:42:31,673 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:31,984 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:42:32,992 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:42:32,992 - new_apply_order.py[line:616]: {'app': 'kencash', 'loan_order_id': '1440491645825716224', 'mobile': '732274942', 'order_status': 35}
INFO - 2021-09-22 09:42:33,879 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:34,248 - new_apply_order.py[line:584]: 放款回调成功！
INFO - 2021-09-22 09:42:34,249 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:42:35,256 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:42:35,256 - new_apply_order.py[line:616]: {'app': 'kencash', 'loan_order_id': '1440491645825716224', 'mobile': '732274942', 'order_status': 40}
INFO - 2021-09-22 09:42:35,257 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:42:35,257 - new_apply_order.py[line:696]: 开始第 kencash【2】次进件……
INFO - 2021-09-22 09:42:35,257 - new_apply_order.py[line:82]: ======【ke测试环境】生成手机号：732274955 ======
INFO - 2021-09-22 09:42:35,596 - new_apply_order.py[line:95]: 732274955 检测用户存在成功！
INFO - 2021-09-22 09:42:35,646 - new_apply_order.py[line:104]: 732274955 短信发送成功！
INFO - 2021-09-22 09:42:35,691 - new_apply_order.py[line:117]: 732274955 注册成功！
INFO - 2021-09-22 09:42:35,744 - new_apply_order.py[line:133]: 732274955 登录短信发送成功！
INFO - 2021-09-22 09:42:35,796 - new_apply_order.py[line:143]: userId=6211881138198945792,mobile=732274955,token=462c00214db0a1c63da482d9c34c5c80 登录成功
INFO - 2021-09-22 09:42:36,528 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:42:36,584 - new_apply_order.py[line:225]: 联系人信息提交成功！
INFO - 2021-09-22 09:42:36,988 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:42:37,003 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:42:37,017 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:42:38,306 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:42:38,341 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:42:38,654 - new_apply_order.py[line:404]: 绑卡成功！
INFO - 2021-09-22 09:42:38,877 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:42:39,910 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:42:40,278 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:40,326 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:42:41,117 - new_apply_order.py[line:483]: 获取token成功！token=bearer f0a0de17-f7e9-46f2-b8d0-60efbc3b30b9！
INFO - 2021-09-22 09:42:41,470 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:41,821 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:42:41,833 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:42:41,843 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:42:43,191 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:43,201 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:42:43,206 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:42:43,562 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:43,687 - new_apply_order.py[line:586]: 放款回调失败！
INFO - 2021-09-22 09:42:43,991 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:42:45,003 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:42:45,004 - new_apply_order.py[line:616]: {'app': 'kencash', 'loan_order_id': '1440491698594254848', 'mobile': '732274955', 'order_status': 35}
INFO - 2021-09-22 09:42:45,907 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:46,130 - new_apply_order.py[line:584]: 放款回调成功！
INFO - 2021-09-22 09:42:46,130 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:42:47,140 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:42:47,140 - new_apply_order.py[line:616]: {'app': 'kencash', 'loan_order_id': '1440491698594254848', 'mobile': '732274955', 'order_status': 40}
INFO - 2021-09-22 09:42:47,141 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:42:47,141 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时24.96s=====
INFO - 2021-09-22 09:42:47,142 - new_apply_order.py[line:696]: 开始第 ikash【1】次进件……
INFO - 2021-09-22 09:42:47,143 - new_apply_order.py[line:82]: ======【ke测试环境】生成手机号：732274967 ======
INFO - 2021-09-22 09:42:47,504 - new_apply_order.py[line:95]: 732274967 检测用户存在成功！
INFO - 2021-09-22 09:42:47,563 - new_apply_order.py[line:104]: 732274967 短信发送成功！
INFO - 2021-09-22 09:42:47,620 - new_apply_order.py[line:117]: 732274967 注册成功！
INFO - 2021-09-22 09:42:47,677 - new_apply_order.py[line:133]: 732274967 登录短信发送成功！
INFO - 2021-09-22 09:42:47,730 - new_apply_order.py[line:143]: userId=6211881188174077952,mobile=732274967,token=5ffc37b6395a912fa8aa3299dcc87819 登录成功
INFO - 2021-09-22 09:42:48,485 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:42:48,536 - new_apply_order.py[line:225]: 联系人信息提交成功！
INFO - 2021-09-22 09:42:48,772 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:42:48,791 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:42:48,809 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:42:49,085 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:42:49,122 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:42:49,426 - new_apply_order.py[line:404]: 绑卡成功！
INFO - 2021-09-22 09:42:49,625 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:42:50,659 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:42:51,015 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:51,060 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:42:51,871 - new_apply_order.py[line:483]: 获取token成功！token=bearer f0a0de17-f7e9-46f2-b8d0-60efbc3b30b9！
INFO - 2021-09-22 09:42:52,220 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:52,544 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:42:52,554 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:42:52,564 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:42:53,933 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:53,948 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:42:53,957 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:42:54,308 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:54,435 - new_apply_order.py[line:586]: 放款回调失败！
INFO - 2021-09-22 09:42:54,740 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:42:55,753 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:42:55,753 - new_apply_order.py[line:616]: {'app': 'ikash', 'loan_order_id': '1440491748674244608', 'mobile': '732274967', 'order_status': 35}
INFO - 2021-09-22 09:42:56,605 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:42:56,795 - new_apply_order.py[line:584]: 放款回调成功！
INFO - 2021-09-22 09:42:56,796 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:42:57,810 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:42:57,810 - new_apply_order.py[line:616]: {'app': 'ikash', 'loan_order_id': '1440491748674244608', 'mobile': '732274967', 'order_status': 40}
INFO - 2021-09-22 09:42:57,811 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:42:57,811 - new_apply_order.py[line:696]: 开始第 ikash【2】次进件……
INFO - 2021-09-22 09:42:57,811 - new_apply_order.py[line:82]: ======【ke测试环境】生成手机号：732274977 ======
INFO - 2021-09-22 09:42:58,159 - new_apply_order.py[line:95]: 732274977 检测用户存在成功！
INFO - 2021-09-22 09:42:58,209 - new_apply_order.py[line:104]: 732274977 短信发送成功！
INFO - 2021-09-22 09:42:58,252 - new_apply_order.py[line:117]: 732274977 注册成功！
INFO - 2021-09-22 09:42:58,302 - new_apply_order.py[line:133]: 732274977 登录短信发送成功！
INFO - 2021-09-22 09:42:58,350 - new_apply_order.py[line:143]: userId=6211881232814055424,mobile=732274977,token=a44a91e36c5c7b2db56ab391283e9c88 登录成功
INFO - 2021-09-22 09:42:59,081 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:42:59,149 - new_apply_order.py[line:225]: 联系人信息提交成功！
INFO - 2021-09-22 09:42:59,726 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:42:59,742 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:42:59,754 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:43:00,073 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:43:00,142 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:43:00,456 - new_apply_order.py[line:404]: 绑卡成功！
INFO - 2021-09-22 09:43:00,647 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:43:01,687 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:43:02,047 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:02,094 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:43:02,878 - new_apply_order.py[line:483]: 获取token成功！token=bearer f0a0de17-f7e9-46f2-b8d0-60efbc3b30b9！
INFO - 2021-09-22 09:43:03,228 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:03,552 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:43:03,562 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:43:03,572 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:43:04,927 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:04,938 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:43:04,947 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:43:05,294 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:05,603 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:43:06,619 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:43:06,619 - new_apply_order.py[line:616]: {'app': 'ikash', 'loan_order_id': '1440491793175810048', 'mobile': '732274977', 'order_status': 35}
INFO - 2021-09-22 09:43:07,477 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:07,702 - new_apply_order.py[line:584]: 放款回调成功！
INFO - 2021-09-22 09:43:07,703 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:43:08,717 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:43:08,718 - new_apply_order.py[line:616]: {'app': 'ikash', 'loan_order_id': '1440491793175810048', 'mobile': '732274977', 'order_status': 40}
INFO - 2021-09-22 09:43:08,718 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:43:08,719 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时21.58s=====
INFO - 2021-09-22 09:43:08,725 - new_apply_order.py[line:696]: 开始第 borrowme【1】次进件……
INFO - 2021-09-22 09:43:08,726 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632274988 ======
INFO - 2021-09-22 09:43:09,108 - new_apply_order.py[line:95]: 01632274988 检测用户存在成功！
INFO - 2021-09-22 09:43:09,950 - new_apply_order.py[line:104]: 01632274988 短信发送成功！
INFO - 2021-09-22 09:43:10,033 - new_apply_order.py[line:117]: 01632274988 注册成功！
INFO - 2021-09-22 09:43:10,149 - new_apply_order.py[line:133]: 01632274988 登录短信发送成功！
INFO - 2021-09-22 09:43:10,258 - new_apply_order.py[line:143]: userId=6211881282147983360,mobile=01632274988,token=3bbd59570b2002c93985332f28e5ceaa 登录成功
INFO - 2021-09-22 09:43:10,368 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:43:10,453 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:43:13,044 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:43:13,059 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:43:13,074 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:43:13,368 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:43:13,414 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:43:14,621 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:43:14,962 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:43:15,771 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:43:16,807 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:43:17,261 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:17,337 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:43:18,178 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:43:18,554 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:19,497 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:43:19,509 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:43:19,522 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:43:20,917 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:20,929 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:43:20,935 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:43:21,238 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:43:22,251 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-09-22 09:43:22,251 - new_apply_order.py[line:616]: {'app': 'borrowme', 'loan_order_id': '1440491842271055872', 'mobile': '01632274988', 'order_status': 32}
INFO - 2021-09-22 09:43:22,262 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:43:22,271 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:43:23,667 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:23,679 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:43:23,684 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:43:24,186 - new_apply_order.py[line:719]: 校验重试查询第2次
ERROR - 2021-09-22 09:43:25,194 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:43:25,194 - new_apply_order.py[line:616]: {'app': 'borrowme', 'loan_order_id': '1440491842271055872', 'mobile': '01632274988', 'order_status': 35}
INFO - 2021-09-22 09:43:25,699 - new_apply_order.py[line:719]: 校验重试查询第3次
ERROR - 2021-09-22 09:43:26,710 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:43:26,710 - new_apply_order.py[line:616]: {'app': 'borrowme', 'loan_order_id': '1440491842271055872', 'mobile': '01632274988', 'order_status': 35}
INFO - 2021-09-22 09:43:27,221 - new_apply_order.py[line:719]: 校验重试查询第4次
INFO - 2021-09-22 09:43:28,238 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:43:28,238 - new_apply_order.py[line:616]: {'app': 'borrowme', 'loan_order_id': '1440491842271055872', 'mobile': '01632274988', 'order_status': 40}
INFO - 2021-09-22 09:43:28,239 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:43:28,239 - new_apply_order.py[line:696]: 开始第 borrowme【2】次进件……
INFO - 2021-09-22 09:43:28,240 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275008 ======
INFO - 2021-09-22 09:43:28,596 - new_apply_order.py[line:95]: 01632275008 检测用户存在成功！
INFO - 2021-09-22 09:43:28,644 - new_apply_order.py[line:104]: 01632275008 短信发送成功！
INFO - 2021-09-22 09:43:28,682 - new_apply_order.py[line:117]: 01632275008 注册成功！
INFO - 2021-09-22 09:43:28,743 - new_apply_order.py[line:133]: 01632275008 登录短信发送成功！
INFO - 2021-09-22 09:43:28,789 - new_apply_order.py[line:143]: userId=6211881360447250432,mobile=01632275008,token=855e940d9ac52e8a76d25469979115ae 登录成功
INFO - 2021-09-22 09:43:28,857 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:43:28,903 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:43:29,215 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:43:29,234 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:43:29,250 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:43:29,508 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:43:29,547 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:43:30,481 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:43:30,769 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:43:31,143 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:43:32,171 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:43:32,548 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:32,598 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:43:33,408 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:43:33,822 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:34,253 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:43:34,266 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:43:34,276 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:43:35,668 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:35,677 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:43:35,681 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:43:35,986 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:43:37,002 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:43:37,002 - new_apply_order.py[line:616]: {'app': 'borrowme', 'loan_order_id': '1440491918015991808', 'mobile': '01632275008', 'order_status': 35}
INFO - 2021-09-22 09:43:37,511 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:43:38,529 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:43:38,529 - new_apply_order.py[line:616]: {'app': 'borrowme', 'loan_order_id': '1440491918015991808', 'mobile': '01632275008', 'order_status': 40}
INFO - 2021-09-22 09:43:38,530 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:43:38,530 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时29.81s=====
INFO - 2021-09-22 09:43:38,534 - new_apply_order.py[line:696]: 开始第 quickcash【1】次进件……
INFO - 2021-09-22 09:43:38,536 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275018 ======
INFO - 2021-09-22 09:43:38,887 - new_apply_order.py[line:95]: 01632275018 检测用户存在成功！
INFO - 2021-09-22 09:43:38,931 - new_apply_order.py[line:104]: 01632275018 短信发送成功！
INFO - 2021-09-22 09:43:38,970 - new_apply_order.py[line:117]: 01632275018 注册成功！
INFO - 2021-09-22 09:43:39,022 - new_apply_order.py[line:133]: 01632275018 登录短信发送成功！
INFO - 2021-09-22 09:43:39,064 - new_apply_order.py[line:143]: userId=6211881403598249984,mobile=01632275018,token=183a1d08b46e7ba1c5b95b0a7d07c423 登录成功
INFO - 2021-09-22 09:43:39,156 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:43:39,206 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:43:39,476 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:43:39,496 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:43:39,516 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:43:39,770 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:43:39,812 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:43:40,833 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:43:41,144 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:43:41,454 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:43:42,494 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:43:42,883 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:42,940 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:43:43,743 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:43:44,106 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:44,438 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:43:44,450 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:43:44,461 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:43:45,831 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:45,848 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:43:45,856 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:43:46,163 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:43:47,179 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:43:47,179 - new_apply_order.py[line:616]: {'app': 'quickcash', 'loan_order_id': '1440491961196351488', 'mobile': '01632275018', 'order_status': 35}
INFO - 2021-09-22 09:43:47,690 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:43:48,706 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:43:48,707 - new_apply_order.py[line:616]: {'app': 'quickcash', 'loan_order_id': '1440491961196351488', 'mobile': '01632275018', 'order_status': 40}
INFO - 2021-09-22 09:43:48,707 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:43:48,708 - new_apply_order.py[line:696]: 开始第 quickcash【2】次进件……
INFO - 2021-09-22 09:43:48,709 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275028 ======
INFO - 2021-09-22 09:43:49,050 - new_apply_order.py[line:95]: 01632275028 检测用户存在成功！
INFO - 2021-09-22 09:43:49,090 - new_apply_order.py[line:104]: 01632275028 短信发送成功！
INFO - 2021-09-22 09:43:49,127 - new_apply_order.py[line:117]: 01632275028 注册成功！
INFO - 2021-09-22 09:43:49,180 - new_apply_order.py[line:133]: 01632275028 登录短信发送成功！
INFO - 2021-09-22 09:43:49,254 - new_apply_order.py[line:143]: userId=6211881446203990016,mobile=01632275028,token=8e5eed08b9620df95e2daeb03ae900c3 登录成功
INFO - 2021-09-22 09:43:49,321 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:43:49,370 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:43:49,591 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:43:49,616 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:43:49,635 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:43:49,892 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:43:49,926 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:43:50,934 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:43:51,231 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:43:51,453 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:43:52,493 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:43:52,866 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:52,910 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:43:53,691 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:43:54,095 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:54,444 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:43:54,457 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:43:54,468 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:43:55,881 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:43:55,901 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:43:55,910 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:43:56,220 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:43:57,238 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:43:57,238 - new_apply_order.py[line:616]: {'app': 'quickcash', 'loan_order_id': '1440492003831451648', 'mobile': '01632275028', 'order_status': 35}
INFO - 2021-09-22 09:43:57,749 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:43:58,770 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:43:58,771 - new_apply_order.py[line:616]: {'app': 'quickcash', 'loan_order_id': '1440492003831451648', 'mobile': '01632275028', 'order_status': 40}
INFO - 2021-09-22 09:43:58,771 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:43:58,772 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时20.24s=====
INFO - 2021-09-22 09:43:58,776 - new_apply_order.py[line:696]: 开始第 borrowme【1】次进件……
INFO - 2021-09-22 09:43:58,777 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275038 ======
INFO - 2021-09-22 09:43:59,137 - new_apply_order.py[line:95]: 01632275038 检测用户存在成功！
INFO - 2021-09-22 09:43:59,179 - new_apply_order.py[line:104]: 01632275038 短信发送成功！
INFO - 2021-09-22 09:43:59,219 - new_apply_order.py[line:117]: 01632275038 注册成功！
INFO - 2021-09-22 09:43:59,276 - new_apply_order.py[line:133]: 01632275038 登录短信发送成功！
INFO - 2021-09-22 09:43:59,326 - new_apply_order.py[line:143]: userId=6211881488516128768,mobile=01632275038,token=6a143dd82668c52eb2f9ac5249dba62f 登录成功
INFO - 2021-09-22 09:43:59,406 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:43:59,479 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:43:59,696 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:43:59,719 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:43:59,734 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:44:00,024 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:44:00,071 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:44:01,041 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:44:01,353 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:44:01,601 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:44:02,641 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:44:03,010 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:03,055 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:44:03,803 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:44:04,164 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:04,520 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:44:04,533 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:44:04,543 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:44:05,910 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:05,929 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:44:05,937 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:44:06,244 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:44:07,263 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:44:07,263 - new_apply_order.py[line:616]: {'app': 'borrowme', 'loan_order_id': '1440492046231670784', 'mobile': '01632275038', 'order_status': 35}
INFO - 2021-09-22 09:44:07,773 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:44:08,783 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:44:08,783 - new_apply_order.py[line:616]: {'app': 'borrowme', 'loan_order_id': '1440492046231670784', 'mobile': '01632275038', 'order_status': 40}
INFO - 2021-09-22 09:44:08,783 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:44:08,784 - new_apply_order.py[line:696]: 开始第 borrowme【2】次进件……
INFO - 2021-09-22 09:44:08,785 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275048 ======
INFO - 2021-09-22 09:44:09,146 - new_apply_order.py[line:95]: 01632275048 检测用户存在成功！
INFO - 2021-09-22 09:44:09,188 - new_apply_order.py[line:104]: 01632275048 短信发送成功！
INFO - 2021-09-22 09:44:09,227 - new_apply_order.py[line:117]: 01632275048 注册成功！
INFO - 2021-09-22 09:44:09,276 - new_apply_order.py[line:133]: 01632275048 登录短信发送成功！
INFO - 2021-09-22 09:44:09,356 - new_apply_order.py[line:143]: userId=6211881530505306112,mobile=01632275048,token=345f44cf4a89952c0fa96183b8fb2420 登录成功
INFO - 2021-09-22 09:44:09,433 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:44:09,479 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:44:09,793 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:44:09,818 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:44:09,835 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:44:11,123 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:44:11,171 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:44:12,128 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:44:12,435 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:44:12,725 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:44:13,767 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:44:14,137 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:14,184 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:44:14,989 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:44:15,351 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:15,731 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:44:15,743 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:44:15,754 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:44:17,121 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:17,141 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:44:17,150 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:44:17,460 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:44:18,474 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:44:18,474 - new_apply_order.py[line:616]: {'app': 'borrowme', 'loan_order_id': '1440492088162127872', 'mobile': '01632275048', 'order_status': 35}
INFO - 2021-09-22 09:44:18,984 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:44:20,007 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:44:20,007 - new_apply_order.py[line:616]: {'app': 'borrowme', 'loan_order_id': '1440492088162127872', 'mobile': '01632275048', 'order_status': 40}
INFO - 2021-09-22 09:44:20,008 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:44:20,008 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时21.23s=====
INFO - 2021-09-22 09:44:20,015 - new_apply_order.py[line:696]: 开始第 moremoney【1】次进件……
INFO - 2021-09-22 09:44:20,015 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275060 ======
INFO - 2021-09-22 09:44:20,361 - new_apply_order.py[line:95]: 01632275060 检测用户存在成功！
INFO - 2021-09-22 09:44:20,406 - new_apply_order.py[line:104]: 01632275060 短信发送成功！
INFO - 2021-09-22 09:44:20,440 - new_apply_order.py[line:117]: 01632275060 注册成功！
INFO - 2021-09-22 09:44:20,489 - new_apply_order.py[line:133]: 01632275060 登录短信发送成功！
INFO - 2021-09-22 09:44:20,532 - new_apply_order.py[line:143]: userId=6211881577540231168,mobile=01632275060,token=cf2afb2a87c206752b82994d7eae7438 登录成功
INFO - 2021-09-22 09:44:20,596 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:44:20,641 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:44:20,840 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:44:20,860 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:44:20,878 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:44:21,138 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:44:21,170 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:44:22,191 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:44:22,490 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:44:22,718 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:44:23,767 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:44:24,128 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:24,172 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:44:24,950 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:44:25,311 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:25,694 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:44:25,705 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:44:25,715 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:44:27,076 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:27,091 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:44:27,099 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:44:27,408 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:44:28,424 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:44:28,424 - new_apply_order.py[line:616]: {'app': 'moremoney', 'loan_order_id': '1440492134974754816', 'mobile': '01632275060', 'order_status': 35}
INFO - 2021-09-22 09:44:28,929 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:44:29,947 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:44:29,947 - new_apply_order.py[line:616]: {'app': 'moremoney', 'loan_order_id': '1440492134974754816', 'mobile': '01632275060', 'order_status': 40}
INFO - 2021-09-22 09:44:29,948 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:44:29,948 - new_apply_order.py[line:696]: 开始第 moremoney【2】次进件……
INFO - 2021-09-22 09:44:29,949 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275069 ======
INFO - 2021-09-22 09:44:30,295 - new_apply_order.py[line:95]: 01632275069 检测用户存在成功！
INFO - 2021-09-22 09:44:30,335 - new_apply_order.py[line:104]: 01632275069 短信发送成功！
INFO - 2021-09-22 09:44:30,373 - new_apply_order.py[line:117]: 01632275069 注册成功！
INFO - 2021-09-22 09:44:30,423 - new_apply_order.py[line:133]: 01632275069 登录短信发送成功！
INFO - 2021-09-22 09:44:30,468 - new_apply_order.py[line:143]: userId=6211881619193864192,mobile=01632275069,token=b22865e5cf84f377677df8f55c05f34e 登录成功
INFO - 2021-09-22 09:44:30,546 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:44:30,595 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:44:30,802 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:44:30,821 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:44:30,841 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:44:31,123 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:44:31,158 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:44:32,129 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:44:32,448 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:44:32,659 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:44:33,699 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:44:34,058 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:34,102 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:44:34,896 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:44:35,260 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:35,633 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:44:35,639 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:44:35,646 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:44:37,015 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:37,034 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:44:37,041 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:44:37,349 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:44:38,370 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:44:38,370 - new_apply_order.py[line:616]: {'app': 'moremoney', 'loan_order_id': '1440492176758411264', 'mobile': '01632275069', 'order_status': 35}
INFO - 2021-09-22 09:44:38,877 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:44:39,893 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:44:39,893 - new_apply_order.py[line:616]: {'app': 'moremoney', 'loan_order_id': '1440492176758411264', 'mobile': '01632275069', 'order_status': 40}
INFO - 2021-09-22 09:44:39,894 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:44:39,894 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时19.88s=====
INFO - 2021-09-22 09:44:39,898 - new_apply_order.py[line:696]: 开始第 creditnaira【1】次进件……
INFO - 2021-09-22 09:44:39,899 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275079 ======
INFO - 2021-09-22 09:44:40,259 - new_apply_order.py[line:95]: 01632275079 检测用户存在成功！
INFO - 2021-09-22 09:44:40,312 - new_apply_order.py[line:104]: 01632275079 短信发送成功！
INFO - 2021-09-22 09:44:40,351 - new_apply_order.py[line:117]: 01632275079 注册成功！
INFO - 2021-09-22 09:44:40,399 - new_apply_order.py[line:133]: 01632275079 登录短信发送成功！
INFO - 2021-09-22 09:44:40,443 - new_apply_order.py[line:143]: userId=6211881661036240896,mobile=01632275079,token=9064640ba3b530466e312b28355a454f 登录成功
INFO - 2021-09-22 09:44:40,511 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:44:40,558 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:44:40,780 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:44:40,797 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:44:40,814 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:44:41,111 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:44:41,143 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:44:42,080 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:44:42,389 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:44:42,625 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:44:43,672 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:44:44,042 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:44,090 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:44:44,916 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:44:45,276 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:45,614 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:44:45,627 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:44:45,637 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:44:47,004 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:47,020 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:44:47,027 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:44:47,331 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:44:48,348 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:44:48,348 - new_apply_order.py[line:616]: {'app': 'creditnaira', 'loan_order_id': '1440492218504318976', 'mobile': '01632275079', 'order_status': 35}
INFO - 2021-09-22 09:44:48,858 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:44:49,878 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:44:49,879 - new_apply_order.py[line:616]: {'app': 'creditnaira', 'loan_order_id': '1440492218504318976', 'mobile': '01632275079', 'order_status': 40}
INFO - 2021-09-22 09:44:49,879 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:44:49,879 - new_apply_order.py[line:696]: 开始第 creditnaira【2】次进件……
INFO - 2021-09-22 09:44:49,880 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275089 ======
INFO - 2021-09-22 09:44:50,227 - new_apply_order.py[line:95]: 01632275089 检测用户存在成功！
INFO - 2021-09-22 09:44:50,269 - new_apply_order.py[line:104]: 01632275089 短信发送成功！
INFO - 2021-09-22 09:44:50,310 - new_apply_order.py[line:117]: 01632275089 注册成功！
INFO - 2021-09-22 09:44:50,363 - new_apply_order.py[line:133]: 01632275089 登录短信发送成功！
INFO - 2021-09-22 09:44:50,407 - new_apply_order.py[line:143]: userId=6211881702803120128,mobile=01632275089,token=4993d7e6024cb15b9df1837ad3f773bf 登录成功
INFO - 2021-09-22 09:44:50,477 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:44:50,523 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:44:50,709 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:44:50,731 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:44:50,748 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:44:50,975 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:44:51,011 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:44:52,051 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:44:52,371 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:44:52,590 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:44:53,634 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:44:53,999 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:54,041 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:44:54,804 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:44:55,161 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:55,454 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:44:55,467 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:44:55,478 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:44:56,835 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:44:56,856 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:44:56,863 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:44:57,171 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:44:58,193 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:44:58,193 - new_apply_order.py[line:616]: {'app': 'creditnaira', 'loan_order_id': '1440492260296364032', 'mobile': '01632275089', 'order_status': 35}
INFO - 2021-09-22 09:44:58,703 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:44:59,719 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:44:59,720 - new_apply_order.py[line:616]: {'app': 'creditnaira', 'loan_order_id': '1440492260296364032', 'mobile': '01632275089', 'order_status': 40}
INFO - 2021-09-22 09:44:59,721 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:44:59,721 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时19.82s=====
INFO - 2021-09-22 09:44:59,725 - new_apply_order.py[line:696]: 开始第 inaira【1】次进件……
INFO - 2021-09-22 09:44:59,726 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275099 ======
INFO - 2021-09-22 09:45:00,069 - new_apply_order.py[line:95]: 01632275099 检测用户存在成功！
INFO - 2021-09-22 09:45:00,113 - new_apply_order.py[line:104]: 01632275099 短信发送成功！
INFO - 2021-09-22 09:45:00,147 - new_apply_order.py[line:117]: 01632275099 注册成功！
INFO - 2021-09-22 09:45:00,197 - new_apply_order.py[line:133]: 01632275099 登录短信发送成功！
INFO - 2021-09-22 09:45:00,241 - new_apply_order.py[line:143]: userId=6211881744083460096,mobile=01632275099,token=17026fbce048e13c5abf7a8413b68d24 登录成功
INFO - 2021-09-22 09:45:00,306 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:45:00,352 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:45:00,539 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:45:00,563 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:45:00,583 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:45:00,862 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:45:00,900 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:45:01,830 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:45:02,124 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:45:02,340 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:45:03,374 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:45:03,756 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:03,834 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:45:04,653 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:45:05,033 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:05,345 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:45:05,357 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:45:05,368 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:45:06,751 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:06,770 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:45:06,779 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:45:07,088 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:45:08,101 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:45:08,102 - new_apply_order.py[line:616]: {'app': 'inaira', 'loan_order_id': '1440492301526372352', 'mobile': '01632275099', 'order_status': 35}
INFO - 2021-09-22 09:45:08,612 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:45:09,626 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:45:09,627 - new_apply_order.py[line:616]: {'app': 'inaira', 'loan_order_id': '1440492301526372352', 'mobile': '01632275099', 'order_status': 40}
INFO - 2021-09-22 09:45:09,627 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:45:09,628 - new_apply_order.py[line:696]: 开始第 inaira【2】次进件……
INFO - 2021-09-22 09:45:09,629 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275109 ======
INFO - 2021-09-22 09:45:09,993 - new_apply_order.py[line:95]: 01632275109 检测用户存在成功！
INFO - 2021-09-22 09:45:10,051 - new_apply_order.py[line:104]: 01632275109 短信发送成功！
INFO - 2021-09-22 09:45:10,099 - new_apply_order.py[line:117]: 01632275109 注册成功！
INFO - 2021-09-22 09:45:10,152 - new_apply_order.py[line:133]: 01632275109 登录短信发送成功！
INFO - 2021-09-22 09:45:10,195 - new_apply_order.py[line:143]: userId=6211881785800007680,mobile=01632275109,token=e44c379050274fc47d104009fdcde3a5 登录成功
INFO - 2021-09-22 09:45:10,266 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:45:10,318 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:45:10,533 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:45:10,551 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:45:10,565 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:45:11,859 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:45:11,891 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:45:12,874 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:45:13,194 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:45:13,441 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:45:14,480 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:45:14,853 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:14,902 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:45:15,689 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:45:16,049 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:16,346 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:45:16,360 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:45:16,378 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:45:17,733 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:17,753 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:45:17,764 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:45:18,073 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:45:19,085 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:45:19,086 - new_apply_order.py[line:616]: {'app': 'inaira', 'loan_order_id': '1440492343326806016', 'mobile': '01632275109', 'order_status': 35}
INFO - 2021-09-22 09:45:19,592 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:45:20,609 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:45:20,609 - new_apply_order.py[line:616]: {'app': 'inaira', 'loan_order_id': '1440492343326806016', 'mobile': '01632275109', 'order_status': 40}
INFO - 2021-09-22 09:45:20,610 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:45:20,610 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时20.89s=====
INFO - 2021-09-22 09:45:20,614 - new_apply_order.py[line:696]: 开始第 runcash【1】次进件……
INFO - 2021-09-22 09:45:20,615 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275120 ======
INFO - 2021-09-22 09:45:20,959 - new_apply_order.py[line:95]: 01632275120 检测用户存在成功！
INFO - 2021-09-22 09:45:21,006 - new_apply_order.py[line:104]: 01632275120 短信发送成功！
INFO - 2021-09-22 09:45:21,048 - new_apply_order.py[line:117]: 01632275120 注册成功！
INFO - 2021-09-22 09:45:21,107 - new_apply_order.py[line:133]: 01632275120 登录短信发送成功！
INFO - 2021-09-22 09:45:21,169 - new_apply_order.py[line:143]: userId=6211881831723442176,mobile=01632275120,token=d5f3e7567afa9bc0285798a5b5bae7b6 登录成功
INFO - 2021-09-22 09:45:21,245 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:45:21,299 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:45:21,496 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:45:21,517 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:45:21,539 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:45:21,785 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:45:21,825 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:45:22,735 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:45:23,032 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:45:23,220 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:45:24,265 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:45:24,626 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:24,672 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:45:25,440 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:45:25,796 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:26,067 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:45:26,080 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:45:26,090 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:45:27,475 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:27,492 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:45:27,501 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:45:27,808 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:45:28,827 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:45:28,828 - new_apply_order.py[line:616]: {'app': 'runcash', 'loan_order_id': '1440492389388652544', 'mobile': '01632275120', 'order_status': 35}
INFO - 2021-09-22 09:45:29,337 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:45:30,349 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:45:30,349 - new_apply_order.py[line:616]: {'app': 'runcash', 'loan_order_id': '1440492389388652544', 'mobile': '01632275120', 'order_status': 40}
INFO - 2021-09-22 09:45:30,350 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:45:30,350 - new_apply_order.py[line:696]: 开始第 runcash【2】次进件……
INFO - 2021-09-22 09:45:30,351 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275130 ======
INFO - 2021-09-22 09:45:30,702 - new_apply_order.py[line:95]: 01632275130 检测用户存在成功！
INFO - 2021-09-22 09:45:30,742 - new_apply_order.py[line:104]: 01632275130 短信发送成功！
INFO - 2021-09-22 09:45:30,775 - new_apply_order.py[line:117]: 01632275130 注册成功！
INFO - 2021-09-22 09:45:30,822 - new_apply_order.py[line:133]: 01632275130 登录短信发送成功！
INFO - 2021-09-22 09:45:30,863 - new_apply_order.py[line:143]: userId=6211881872542408704,mobile=01632275130,token=327f333281e2ca6f6c6ce334226c0524 登录成功
INFO - 2021-09-22 09:45:30,967 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:45:31,023 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:45:31,223 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:45:31,240 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:45:31,256 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:45:31,514 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:45:31,548 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:45:32,521 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:45:32,822 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:45:33,061 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:45:34,103 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:45:34,458 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:34,497 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:45:35,342 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:45:35,707 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:36,087 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:45:36,101 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:45:36,112 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:45:37,474 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:37,496 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:45:37,504 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:45:37,814 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:45:38,832 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:45:38,832 - new_apply_order.py[line:616]: {'app': 'runcash', 'loan_order_id': '1440492430216007680', 'mobile': '01632275130', 'order_status': 35}
INFO - 2021-09-22 09:45:39,343 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:45:40,358 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:45:40,359 - new_apply_order.py[line:616]: {'app': 'runcash', 'loan_order_id': '1440492430216007680', 'mobile': '01632275130', 'order_status': 40}
INFO - 2021-09-22 09:45:40,360 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:45:40,360 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时19.75s=====
INFO - 2021-09-22 09:45:40,364 - new_apply_order.py[line:696]: 开始第 formoney【1】次进件……
INFO - 2021-09-22 09:45:40,365 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275140 ======
INFO - 2021-09-22 09:45:40,716 - new_apply_order.py[line:95]: 01632275140 检测用户存在成功！
INFO - 2021-09-22 09:45:40,770 - new_apply_order.py[line:104]: 01632275140 短信发送成功！
INFO - 2021-09-22 09:45:40,807 - new_apply_order.py[line:117]: 01632275140 注册成功！
INFO - 2021-09-22 09:45:40,854 - new_apply_order.py[line:133]: 01632275140 登录短信发送成功！
INFO - 2021-09-22 09:45:40,895 - new_apply_order.py[line:143]: userId=6211881914607083520,mobile=01632275140,token=59b4d410e23c16bfc9c1c6676997c146 登录成功
INFO - 2021-09-22 09:45:40,958 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:45:41,006 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:45:41,228 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:45:41,248 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:45:41,266 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:45:41,540 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:45:41,580 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:45:42,537 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:45:42,830 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:45:43,048 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:45:44,088 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:45:44,449 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:44,503 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:45:45,298 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:45:45,656 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:46,062 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:45:46,074 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:45:46,085 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:45:47,442 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:47,462 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:45:47,469 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:45:47,773 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:45:48,792 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:45:48,794 - new_apply_order.py[line:616]: {'app': 'formoney', 'loan_order_id': '1440492472041607168', 'mobile': '01632275140', 'order_status': 35}
INFO - 2021-09-22 09:45:49,303 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:45:50,315 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:45:50,316 - new_apply_order.py[line:616]: {'app': 'formoney', 'loan_order_id': '1440492472041607168', 'mobile': '01632275140', 'order_status': 40}
INFO - 2021-09-22 09:45:50,317 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:45:50,318 - new_apply_order.py[line:696]: 开始第 formoney【2】次进件……
INFO - 2021-09-22 09:45:50,318 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275150 ======
INFO - 2021-09-22 09:45:50,660 - new_apply_order.py[line:95]: 01632275150 检测用户存在成功！
INFO - 2021-09-22 09:45:50,702 - new_apply_order.py[line:104]: 01632275150 短信发送成功！
INFO - 2021-09-22 09:45:50,740 - new_apply_order.py[line:117]: 01632275150 注册成功！
INFO - 2021-09-22 09:45:50,797 - new_apply_order.py[line:133]: 01632275150 登录短信发送成功！
INFO - 2021-09-22 09:45:50,840 - new_apply_order.py[line:143]: userId=6211881956273299456,mobile=01632275150,token=fecc5ecccb3c9b3e2008c7c534326b62 登录成功
INFO - 2021-09-22 09:45:50,931 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:45:50,990 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:45:51,297 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:45:51,316 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:45:51,330 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:45:51,609 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:45:51,643 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:45:52,586 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:45:52,852 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:45:53,070 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:45:54,103 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:45:54,457 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:54,512 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:45:55,289 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:45:55,636 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:55,886 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:45:55,893 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:45:55,901 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:45:57,258 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:45:57,272 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:45:57,278 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:45:57,584 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:45:58,598 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:45:58,599 - new_apply_order.py[line:616]: {'app': 'formoney', 'loan_order_id': '1440492514018201600', 'mobile': '01632275150', 'order_status': 35}
INFO - 2021-09-22 09:45:59,108 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:46:00,124 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:46:00,125 - new_apply_order.py[line:616]: {'app': 'formoney', 'loan_order_id': '1440492514018201600', 'mobile': '01632275150', 'order_status': 40}
INFO - 2021-09-22 09:46:00,126 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:46:00,126 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时19.76s=====
INFO - 2021-09-22 09:46:00,130 - new_apply_order.py[line:696]: 开始第 Gotocash【1】次进件……
INFO - 2021-09-22 09:46:00,131 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275160 ======
INFO - 2021-09-22 09:46:00,492 - new_apply_order.py[line:95]: 01632275160 检测用户存在成功！
INFO - 2021-09-22 09:46:00,539 - new_apply_order.py[line:104]: 01632275160 短信发送成功！
INFO - 2021-09-22 09:46:00,576 - new_apply_order.py[line:117]: 01632275160 注册成功！
INFO - 2021-09-22 09:46:00,624 - new_apply_order.py[line:133]: 01632275160 登录短信发送成功！
INFO - 2021-09-22 09:46:00,666 - new_apply_order.py[line:143]: userId=6211881997536862208,mobile=01632275160,token=d5ca986e40351ef69c09038212d6ac09 登录成功
INFO - 2021-09-22 09:46:00,736 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:46:00,784 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:46:00,977 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:46:01,000 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:46:01,017 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:46:01,270 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:46:01,304 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:46:02,295 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:46:02,605 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:46:02,826 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:46:03,870 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:46:04,230 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:04,274 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:46:05,051 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:46:05,408 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:05,742 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:46:05,755 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:46:05,768 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:46:07,115 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:07,131 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:46:07,138 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:46:07,445 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:46:08,461 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:46:08,461 - new_apply_order.py[line:616]: {'app': 'Gotocash', 'loan_order_id': '1440492555025911808', 'mobile': '01632275160', 'order_status': 35}
INFO - 2021-09-22 09:46:08,970 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:46:09,985 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:46:09,986 - new_apply_order.py[line:616]: {'app': 'Gotocash', 'loan_order_id': '1440492555025911808', 'mobile': '01632275160', 'order_status': 40}
INFO - 2021-09-22 09:46:09,986 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:46:09,987 - new_apply_order.py[line:696]: 开始第 Gotocash【2】次进件……
INFO - 2021-09-22 09:46:09,988 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275169 ======
INFO - 2021-09-22 09:46:10,352 - new_apply_order.py[line:95]: 01632275169 检测用户存在成功！
INFO - 2021-09-22 09:46:10,398 - new_apply_order.py[line:104]: 01632275169 短信发送成功！
INFO - 2021-09-22 09:46:10,440 - new_apply_order.py[line:117]: 01632275169 注册成功！
INFO - 2021-09-22 09:46:10,496 - new_apply_order.py[line:133]: 01632275169 登录短信发送成功！
INFO - 2021-09-22 09:46:10,550 - new_apply_order.py[line:143]: userId=6211882038905282560,mobile=01632275169,token=73f58d9e80321797eb6d7eb608bef347 登录成功
INFO - 2021-09-22 09:46:10,644 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:46:10,701 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:46:10,907 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:46:10,928 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:46:10,945 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:46:11,237 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:46:11,277 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:46:12,284 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:46:12,580 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:46:12,788 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:46:13,829 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:46:14,185 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:14,227 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:46:15,007 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:46:15,365 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:15,744 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:46:15,756 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:46:15,768 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:46:17,162 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:17,174 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:46:17,178 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:46:17,483 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:46:18,490 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:46:18,490 - new_apply_order.py[line:616]: {'app': 'Gotocash', 'loan_order_id': '1440492596612435968', 'mobile': '01632275169', 'order_status': 35}
INFO - 2021-09-22 09:46:18,991 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:46:19,999 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:46:19,999 - new_apply_order.py[line:616]: {'app': 'Gotocash', 'loan_order_id': '1440492596612435968', 'mobile': '01632275169', 'order_status': 40}
INFO - 2021-09-22 09:46:20,000 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:46:20,000 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时19.87s=====
INFO - 2021-09-22 09:46:20,005 - new_apply_order.py[line:696]: 开始第 Gotcash【1】次进件……
INFO - 2021-09-22 09:46:20,006 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275180 ======
INFO - 2021-09-22 09:46:20,347 - new_apply_order.py[line:95]: 01632275180 检测用户存在成功！
INFO - 2021-09-22 09:46:20,392 - new_apply_order.py[line:104]: 01632275180 短信发送成功！
INFO - 2021-09-22 09:46:20,428 - new_apply_order.py[line:117]: 01632275180 注册成功！
INFO - 2021-09-22 09:46:20,483 - new_apply_order.py[line:133]: 01632275180 登录短信发送成功！
INFO - 2021-09-22 09:46:20,535 - new_apply_order.py[line:143]: userId=6211882080818962432,mobile=01632275180,token=b0e451ec065061eea7084aeda2d24e66 登录成功
INFO - 2021-09-22 09:46:20,613 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:46:20,662 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:46:20,863 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:46:20,876 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:46:20,887 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:46:21,137 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:46:21,169 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:46:22,184 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:46:22,489 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:46:22,705 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:46:23,730 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:46:24,077 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:24,113 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:46:24,902 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:46:25,255 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:25,570 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:46:25,576 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:46:25,584 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:46:26,940 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:26,959 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:46:26,967 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:46:27,275 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:46:28,295 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:46:28,295 - new_apply_order.py[line:616]: {'app': 'Gotcash', 'loan_order_id': '1440492638391898112', 'mobile': '01632275180', 'order_status': 35}
INFO - 2021-09-22 09:46:28,803 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:46:29,815 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:46:29,816 - new_apply_order.py[line:616]: {'app': 'Gotcash', 'loan_order_id': '1440492638391898112', 'mobile': '01632275180', 'order_status': 40}
INFO - 2021-09-22 09:46:29,816 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:46:29,816 - new_apply_order.py[line:696]: 开始第 Gotcash【2】次进件……
INFO - 2021-09-22 09:46:29,817 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275189 ======
INFO - 2021-09-22 09:46:30,158 - new_apply_order.py[line:95]: 01632275189 检测用户存在成功！
INFO - 2021-09-22 09:46:30,195 - new_apply_order.py[line:104]: 01632275189 短信发送成功！
INFO - 2021-09-22 09:46:30,232 - new_apply_order.py[line:117]: 01632275189 注册成功！
INFO - 2021-09-22 09:46:30,281 - new_apply_order.py[line:133]: 01632275189 登录短信发送成功！
INFO - 2021-09-22 09:46:30,325 - new_apply_order.py[line:143]: userId=6211882121944113152,mobile=01632275189,token=09a5c1016b980b4261b3b97acbf64c79 登录成功
INFO - 2021-09-22 09:46:30,394 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:46:30,443 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:46:30,618 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:46:30,633 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:46:30,646 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:46:30,891 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:46:30,923 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:46:31,922 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:46:32,221 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:46:32,412 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:46:33,449 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:46:33,802 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:33,844 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:46:34,641 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:46:34,999 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:35,328 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:46:35,341 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:46:35,351 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:46:36,718 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:36,735 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:46:36,744 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:46:37,052 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:46:38,069 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:46:38,070 - new_apply_order.py[line:616]: {'app': 'Gotcash', 'loan_order_id': '1440492679428968448', 'mobile': '01632275189', 'order_status': 35}
INFO - 2021-09-22 09:46:38,580 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:46:39,593 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:46:39,594 - new_apply_order.py[line:616]: {'app': 'Gotcash', 'loan_order_id': '1440492679428968448', 'mobile': '01632275189', 'order_status': 40}
INFO - 2021-09-22 09:46:39,595 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:46:39,595 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时19.59s=====
INFO - 2021-09-22 09:46:39,599 - new_apply_order.py[line:696]: 开始第 faircash【1】次进件……
INFO - 2021-09-22 09:46:39,600 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275199 ======
INFO - 2021-09-22 09:46:39,963 - new_apply_order.py[line:95]: 01632275199 检测用户存在成功！
INFO - 2021-09-22 09:46:40,014 - new_apply_order.py[line:104]: 01632275199 短信发送成功！
INFO - 2021-09-22 09:46:40,051 - new_apply_order.py[line:117]: 01632275199 注册成功！
INFO - 2021-09-22 09:46:40,114 - new_apply_order.py[line:133]: 01632275199 登录短信发送成功！
INFO - 2021-09-22 09:46:40,174 - new_apply_order.py[line:143]: userId=6211882163123789824,mobile=01632275199,token=83c8dcf44ea8828cf002f7c20410617f 登录成功
INFO - 2021-09-22 09:46:40,248 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:46:40,302 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:46:40,545 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:46:40,564 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:46:40,580 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:46:40,867 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:46:40,902 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:46:41,913 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:46:42,213 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:46:42,477 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:46:43,521 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:46:43,880 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:43,918 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:46:44,677 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:46:45,035 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:45,346 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:46:45,359 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:46:45,371 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:46:46,741 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:46,759 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:46:46,768 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:46:47,076 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:46:48,097 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:46:48,097 - new_apply_order.py[line:616]: {'app': 'faircash', 'loan_order_id': '1440492720801583104', 'mobile': '01632275199', 'order_status': 35}
INFO - 2021-09-22 09:46:48,607 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:46:49,627 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:46:49,627 - new_apply_order.py[line:616]: {'app': 'faircash', 'loan_order_id': '1440492720801583104', 'mobile': '01632275199', 'order_status': 40}
INFO - 2021-09-22 09:46:49,628 - new_apply_order.py[line:736]: ===========完成第【1】次进件===========
INFO - 2021-09-22 09:46:49,628 - new_apply_order.py[line:696]: 开始第 faircash【2】次进件……
INFO - 2021-09-22 09:46:49,629 - new_apply_order.py[line:82]: ======【nga测试环境】生成手机号：01632275209 ======
INFO - 2021-09-22 09:46:49,971 - new_apply_order.py[line:95]: 01632275209 检测用户存在成功！
INFO - 2021-09-22 09:46:50,018 - new_apply_order.py[line:104]: 01632275209 短信发送成功！
INFO - 2021-09-22 09:46:50,062 - new_apply_order.py[line:117]: 01632275209 注册成功！
INFO - 2021-09-22 09:46:50,139 - new_apply_order.py[line:133]: 01632275209 登录短信发送成功！
INFO - 2021-09-22 09:46:50,185 - new_apply_order.py[line:143]: userId=6211882205112967168,mobile=01632275209,token=468dae9dfe682cb235a193166879cd78 登录成功
INFO - 2021-09-22 09:46:50,305 - new_apply_order.py[line:205]: 个人信息提交成功！
INFO - 2021-09-22 09:46:50,360 - new_apply_order.py[line:216]: 联系人信息提交成功！
INFO - 2021-09-22 09:46:50,579 - new_apply_order.py[line:238]: 创建预审订单成功！
INFO - 2021-09-22 09:46:50,601 - new_apply_order.py[line:246]: 预审状态修改为通过,更新条数 1
INFO - 2021-09-22 09:46:50,623 - new_apply_order.py[line:249]: 更新初始额度！更新条数 1
INFO - 2021-09-22 09:46:50,884 - new_apply_order.py[line:266]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-09-22 09:46:50,919 - new_apply_order.py[line:276]: 视频认证通过！
INFO - 2021-09-22 09:46:51,936 - new_apply_order.py[line:367]: bvn和银行卡绑卡认证通过！
INFO - 2021-09-22 09:46:52,231 - new_apply_order.py[line:388]: user更新1条
INFO - 2021-09-22 09:46:52,461 - new_apply_order.py[line:426]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-09-22 09:46:53,488 - new_apply_order.py[line:432]: 订单表更新1条，信审更新1条
INFO - 2021-09-22 09:46:53,852 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:53,900 - new_apply_order.py[line:461]: 订单回调复审通过成功！
INFO - 2021-09-22 09:46:54,704 - new_apply_order.py[line:483]: 获取token成功！token=bearer 7600499d-cf20-463d-af9e-ad588a034a44！
INFO - 2021-09-22 09:46:55,069 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:55,417 - new_apply_order.py[line:501]: 后台已触发放款成功！
INFO - 2021-09-22 09:46:55,429 - new_apply_order.py[line:515]: xxl_job web 登录成功！
INFO - 2021-09-22 09:46:55,440 - new_apply_order.py[line:531]: xxl_job 放款准备作业执行成功！
INFO - 2021-09-22 09:46:56,793 - new_apply_order.py[line:446]: 查询loan_order_id成功！
INFO - 2021-09-22 09:46:56,812 - new_apply_order.py[line:539]: 修改放款准备完成时间成功！
INFO - 2021-09-22 09:46:56,820 - new_apply_order.py[line:547]: xxl_job 放款完成作业执行成功！
INFO - 2021-09-22 09:46:57,129 - new_apply_order.py[line:719]: 校验重试查询第1次
ERROR - 2021-09-22 09:46:58,145 - new_apply_order.py[line:615]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-09-22 09:46:58,145 - new_apply_order.py[line:616]: {'app': 'faircash', 'loan_order_id': '1440492762971115520', 'mobile': '01632275209', 'order_status': 35}
INFO - 2021-09-22 09:46:58,655 - new_apply_order.py[line:719]: 校验重试查询第2次
INFO - 2021-09-22 09:46:59,671 - new_apply_order.py[line:613]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-09-22 09:46:59,672 - new_apply_order.py[line:616]: {'app': 'faircash', 'loan_order_id': '1440492762971115520', 'mobile': '01632275209', 'order_status': 40}
INFO - 2021-09-22 09:46:59,672 - new_apply_order.py[line:736]: ===========完成第【2】次进件===========
INFO - 2021-09-22 09:46:59,673 - new_apply_order.py[line:739]: ======完成第【2】次进件,耗时20.07s=====
